### ISSUE TITLE
Please provide the old version of the software, thank you very much.！！！！！

### ISSUE THREAD

**Issue by Coforgpaper** [a2x/cs2-dumper#100]

**Comment by Xsintashi** [comment]
https://github.com/a2x/cs2-dumper/tree/7833227736608bd91db66372d0985236fb662f33

**Comment by Coforgpaper** [comment]
> https://github.com/a2x/cs2-dumper/tree/7833227736608bd91db66372d0985236fb662f33

// Generated using https://github.com/a2x/cs2-dumper
// 2024-04-03 13:52:55.673660100 UTC

#![allow(non_upper_case_globals, non_camel_case_types, unused)]

pub mod cs2_dumper {
    pub mod schemas {
    }
}
Still, it won't have any information. I mean, I want the previous software to get dumper, which will generate client.rs instead of client.dll.rs
