### ISSUE TITLE
shit update so here are some suggestions

### ISSUE THREAD

**Issue by pQ96VJItXy0oe8FYcrYsTDXKG7CKm9jX** [a2x/cs2-dumper#102]
1. fix the bug where some output files are just empty
2. have an option where it can output files that were similar to the previous update
3. don't randomly remove offsets that can be useful (eg. dwForceJump) 
4. or completely revert changes and go back to the old update

**Comment by Suspectxyzz** [comment]
client.dll.json is empty

**Comment by Vaneeyo** [comment]
dwForceJump is still there but is now named jump and should be in the button file instead of the offsets file
