### ISSUE TITLE
Values can be out of range for their datatype

### ISSUE THREAD

**Issue by superyu1337** [a2x/cs2-dumper#104]
https://github.com/a2x/cs2-dumper/blob/3a935f5d73ae0ce8299ffe444da44a3596027ea2/output/engine2.dll.rs#L42
This Enum variant is out of range for it's datatype, rust is throwing a "literal out of range" error on compile.
Can in theory be fixed by `#[allow(overflowing_literals)]`, but I think the issue is in the generation of the files? Not sure.

**Comment by a2x** [comment]
Thanks for the heads up.

**Comment by a2x** [comment]
Fixed in https://github.com/a2x/cs2-dumper/commit/9f37324266c56e4b02a037e47fd3e73945ba3c14.
