### ISSUE TITLE
Some output offsets are empty if self generated

### ISSUE THREAD

**Issue by lukrei** [a2x/cs2-dumper#105]
Hello since today i have the problem that 2 files are empty and does not contain offsets if self generated:
output\client.dll.rs
output\engine2.dll.rs

I compiled the program in linux and run it aferwards with:
sudo ./cs2-dumper -c qemu

I also tried to run the exe file in windows but same behaviour.

**Comment by Coforgpaper** [comment]
@a2x me too
https://github.com/superyu1337/radarflow2/issues/13
