### ISSUE TITLE
Quick PSA

### ISSUE THREAD

**Issue by a2x** [a2x/cs2-dumper#106]
I am aware that the dumper is currently broken due to the recent CS2 update. This has affected not only this dumper but also other dumpers, including internals that rely on schema parsing. Unfortunately, due to life & work, I won't be able to address the current issues again until tonight.

For now, I will briefly mention some things I've found that have changed in the recent update:
- The `class_bindings` offset in `SchemaSystemTypeScope` has changed from `0x5B8` to `0x5C0`.
- The `enum_bindings` offset in `SchemaSystemTypeScope` has changed from `0x2E00` to `0x2E50`.
- There have been changes to the structure of the `CUtlTSHash` class. (There's also currently a bug in the `elements` method).

Other things I will address:
- Offsets like `dwForceJump` are now defined in the newly generated button files. (Names are just pulled from memory currently, so `jump` will be written instead of `dwForceJump`).
- Linux support will be added back to the `linux` branch very soon.

Also, please avoid opening the same issues repeatedly. If you are going to open an issue, please provide me with as much information as possible; otherwise, it's not very helpful. For example, I've seen some people complaining about missing or incorrect offsets but failing to mention which ones in particular.

**Comment by Txreq** [comment]
Your efforts are really appreciated mate, thank you :D

**Comment by WolverinDEV** [comment]
> There have been changes to the structure of the CUtlTSHash class

They seemed to have changed quite a thing for the hash map implementation.  
You may want to use the declared class/enum tree located at `0x4C8`/`0x4F8`.  
```
// pub comperator: Fn(...) -> bool = 0x00,
pub entries: Ptr<[DeclaredListEntry]> = 0x08,
pub entry_count: u16 = 0x1A,
pub start_node: i16 = 0x18,
```

Declared enum and class entries seem to have the same structure:  
```
pub left_leaf: i16 = 0x00,
pub right_leaf: i16 = 0x02,

pub entry: Ptr<()> = 0x10,
```
`entry` is a pointer to `CSchemaTypeDeclaredEnum` or `CSchemaTypeDeclaredClass` both containing at offset 0x20 a pointer to the `CSchemaEnumBinding`/`CSchemaClassBinding`.
