### ISSUE TITLE
GetLocalPlayer 

### ISSUE THREAD

**Issue by externalkji** [a2x/cs2-dumper#11]
Thank you for your release here!
Would it be possible to request further investigation on the clientstate?

Today I found at 0xF0 the PlayerSlot on Server
dwNetworkGameClient = 0x48BAB0;
int PlayerSlot = dwNetworkGameClient + 0xF0

but I am still looking for GetLocalPlayer if you happend to find it could you please share? :-) Thank you

**Comment by externalkji** [comment]
I know there is LocalPlayerController and dwLocalPlayer but I'm looking for the ClientState Entity one

**Comment by cr1ngeman** [comment]
> I know there is LocalPlayerController and dwLocalPlayer but I'm looking for the ClientState Entity one

Where did you find dwLocalPlayer? name file?

**Comment by a2x** [comment]
Added in 96a378be0b59b4bd54ab4ac034548d1aaa01f2fb
