### ISSUE TITLE
Tool output offset is still empty. [game build is 14001, but offsets are for 14000] QAQ

### ISSUE THREAD

**Issue by Coforgpaper** [a2x/cs2-dumper#110]
Tool output offset is still empty. [game build is 14001, but offsets are for 14000] QAQ

**Comment by a2x** [comment]
Did you compile it or use the latest release? I haven't updated the latest release yet so that may be why.

**Comment by Coforgpaper** [comment]
oh latest release? okay  Waiting for your update, thank you very much.

**Comment by a2x** [comment]
Try again now, please.

**Comment by Coforgpaper** [comment]
ok!!!!

**Comment by Coforgpaper** [comment]
Thank you for your unremitting update, and now the program can be used normally!

**Comment by Coforgpaper** [comment]
The tool can be used, but my program still prompts.
[game build is 14001, but offsets are for 14000]

**Comment by a2x** [comment]
Which offsets are invalid for you?

**Comment by Coforgpaper** [comment]
I am not the author of this program, this program is https://github.com/superyu1337/radarflow2.
You only need to update these three files: client, engine2 and offset.
![c9d302f3520871a1bf408b861e28656b](https://github.com/a2x/cs2-dumper/assets/163156194/0ccb9d53-cf01-47a3-9956-796961cc5abc)

**Comment by Coforgpaper** [comment]
I am not the author of this program, this program is https://github.com/superyu1337/radarflow2.
my only need to update these three files: client, engine2 and offset.
![c9d302f3520871a1bf408b861e28656b](https://github.com/a2x/cs2-dumper/assets/163156194/afacc645-036d-4729-8b9a-4537b8304e0f)
