### ISSUE TITLE
How to check if game loaded? ESP crashing if enabled and I connect or disconnect in a match

### ISSUE THREAD

**Issue by Kuhicop** [a2x/cs2-dumper#111]
Hi, thanks for this repository I really appreciate this work :)

My ESP is crashing when it's enabled and I try to join a match, disconnect from a match or the map changes.
So, to prevent the crash, I'm trying to check if the game is loaded before scanning entity list, so I've been testing with this:
```
namespace C_CSGameRulesProxy {
    constexpr std::ptrdiff_t m_pGameRules = 0x550; // C_CSGameRules*
}
namespace C_CSGameRules {
    constexpr std::ptrdiff_t m_gamePhase = 0x78; // int32
}
```

I understand that C_CSGameRules is at [C_CSGameRulesProxy+0x550]... But, how can I find the address of C_CSGameRulesProxy?

I can see this in IDA Class informer:
![image](https://github.com/a2x/cs2-dumper/assets/27239965/ebbc6fdc-cc13-447e-ac0a-05de7c6f4751)

Thanks in advance <3

**Comment by Xsintashi** [comment]
Call Engine VFunc isInGame or isInConnected

**Comment by Kuhicop** [comment]
> Engine VFunc isInGame or isInConnected

I'm internal c++, there is any procedure to find Engine VFunc isInGame/isInConnected or it's pure reversing trial and error?

I don't know how to find the Engine VFuncs :(

**Comment by Xsintashi** [comment]
> > Engine VFunc isInGame or isInConnected
> 
> I'm internal c++, there is any procedure to find Engine VFunc isInGame/isInConnected or it's pure reversing trial and error?
> 
> EDIT after investigation: ![image](https://private-user-images.githubusercontent.com/27239965/319992255-820dd4d6-91a6-4015-a200-ad10c99666a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDY2NTIsIm5iZiI6MTcxMjM0NjM1MiwicGF0aCI6Ii8yNzIzOTk2NS8zMTk5OTIyNTUtODIwZGQ0ZDYtOTFhNi00MDE1LWEyMDAtYWQxMGM5OTY2NmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE5NDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NDM2NjUzYzA5ZjNhNjM0ZGVjODZkYTg0ZmY0NDY0ZDdlZjU0NzliMDU0YmUxZDFjMGQ5ZWE2ZjI1M2IzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gluepZEObtt_VBAEvZ_AQUc1jpVicGYKBDz5DRlvKDE)
> 
> ![image](https://private-user-images.githubusercontent.com/27239965/319992513-b460dbb6-3668-49ec-91ae-61d04632c555.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDY2NTIsIm5iZiI6MTcxMjM0NjM1MiwicGF0aCI6Ii8yNzIzOTk2NS8zMTk5OTI1MTMtYjQ2MGRiYjYtMzY2OC00OWVjLTkxYWUtNjFkMDQ2MzJjNTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE5NDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkOTUxYjgxZWQ4Yjk4N2RlZGIyNTNhMWEzMTUzMDMxMTcwMGRhMTI4NTY0NDdlY2FhMDAxY2U5ZjRjMDhmN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ez1hZjI-4obtUbjqmzI2psm8F6d2uyI2Gw7LPGgf7Qg)
> 
> But I don't know how to continue

isingame has 32 index, isconnected has 33

**Comment by a2x** [comment]
If you're external, just replicate what the `CEngineClient::IsInGame` and `CEngineClient::IsConnected` functions do.

For example:
```rs
let engine2_base = process.module_by_name("engine2.dll")?.base;

let network_game_client = process.read_addr64(engine2_base + 0x514AC8)?;

let is_background_map: u8 = process.read(network_game_client + 0x281443)?; // CNetworkGameClientBase::IsBackgroundMap (VTable Index 17)
let sign_on_state: u32 = process.read(network_game_client + 0x240)?;

let is_connected = sign_on_state >= 2;
let is_in_game = is_background_map == 0 && sign_on_state >= 6;

println!("is connected: {}, is in game: {}", is_connected, is_in_game);
```

**Comment by Kuhicop** [comment]
> ```rust
> 0x514AC8
> ```

Hi sorry to reply after 2 weeks, I've been taking Tramadol and wasn't able to do shit

I'm lost getting this address: 0x514AC8
I can find all the rest except that one :(

How do you find that 0x514AC8?
![image](https://github.com/a2x/cs2-dumper/assets/27239965/978d5ff1-8288-41dc-bf68-64bd83807c72)

I can see the code you mention but if I put a breakpoint and play a game it never triggers:
![image](https://github.com/a2x/cs2-dumper/assets/27239965/594e225e-6a21-44ce-a443-ca6093273776)

Please help, I only need to find that address and I'm finish :D

**Comment by a2x** [comment]
https://github.com/a2x/cs2-dumper/blob/bda7f86ef346a604c49f24bc3c3c2a27723af11a/output/offsets.hpp#L33

Signature for the relevant instruction: `48 89 3D ? ? ? ? 48 8D 15`
