### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by dsdggdfgdrgdrgdrgdrg** [a2x/cs2-dumper#115]
when i start a command, it says unable to get offsets, why is that?

**Comment by a2x** [comment]
You're going to need to provide more information. I can't deduce anything based on what you've said. Screenshots, anything...

**Comment by dsdggdfgdrgdrgdrgdrg** [comment]
i open main, and it says , unable to get offsets, and it closed
![imagen_2024-04-06_004217607](https://github.com/a2x/cs2-dumper/assets/56462706/d4623fdd-9b6b-429c-896b-dfc7a3180c6f)

**Comment by a2x** [comment]
Not related to this project.
