### ISSUE TITLE
Question: Which flag do I need to use for checking if LocalPlayer is on the ground?

### ISSUE THREAD

**Issue by MehPropy** [a2x/cs2-dumper#12]
I am new to this and I am struggling with which flag I need to use for checking if localplayer is on the ground.

This is the flag I used for "checking if the localplayer is on the ground" from **C_BaseEntity**:
`constexpr std::ptrdiff_t m_fFlags = 0x3C8; // uint32_t`
This offset for the LocalPlayer:
`constexpr std::ptrdiff_t dwLocalPlayerPawn = 0x187AC48;`
And this one for checking if the player is alive from **CCSPlayerController**:
`constexpr std::ptrdiff_t m_iPawnHealth = 0x808; // uint32_t`

But it dosen't work, so I assumed it is because of an incorrect flag offset 

I am also not sure what is the difference between **dwLocalPlayerController** and **dwLocalPlayerPawn**, if somebody can explain this to me I would appriciate it a lot.

**Comment by gr1ndy** [comment]
fl_onground = (1 << 0)

so basically "m_fFlags & 1"

and to check if local is in air u just add a " ! " before m_fFlags

**Comment by MehPropy** [comment]
Can you be more specific? I don't understand what I am supposed to do.
