### ISSUE TITLE
anyone have CrosshairId?

### ISSUE THREAD

**Issue by boyo3473** [a2x/cs2-dumper#127]

**Comment by arrayffs** [comment]
```
cs2_dumper::schemas::client_dll::C_CSPlayerPawnBase::m_iIDEntIndex = 0x15A4;
```

make sure to have client.dll header files included

**Comment by boyo3473** [comment]
> ```
> cs2_dumper::schemas::client_dll::C_CSPlayerPawnBase::m_iIDEntIndex = 0x15A4;
> ```
> 
> make sure to have client.dll header files included
what file did you get that from?

**Comment by a2x** [comment]
> > ```
> > cs2_dumper::schemas::client_dll::C_CSPlayerPawnBase::m_iIDEntIndex = 0x15A4;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > make sure to have client.dll header files included
> > what file did you get that from?

https://github.com/a2x/cs2-dumper/blob/bda7f86ef346a604c49f24bc3c3c2a27723af11a/output/client.dll.hpp#L2141
