### ISSUE TITLE
After the CS2 update, my program is completely useless

### ISSUE THREAD

**Issue by lum0022** [a2x/cs2-dumper#130]
Can you provide an old version of dump? My program only supports the old format and cannot be used after today's update. The software address is https://github.com/Mzzzj/CS2_DMA_Extrnal/tree/main
I found that dwBuildNumber dwInterfaceLinkList dwForceCrouch is missing from offsets.json. I'm not sure if these three factors are causing it, thank you

**Comment by a2x** [comment]
Open an issue there instead, please.
