### ISSUE TITLE
Is offset incorrect?

### ISSUE THREAD

**Issue by qixu666777** [a2x/cs2-dumper#132]
Hello, after the game is updated, I updated the offset in your project, but I reported an error during the compilation, I hope you can fix it, thank you very much!
Here are the error codes：
error[E0425]: cannot find value in module
--> src/dma/context/mod.rs:21:115
|
21 | ...fsets::engine2_dll::dwBuildNumber)?;
| ^^^^^^^^^^^^^ not found in dwBuildNumbercs2dumper::offsets::engine2_dllcs2dumper::offsets::engine2_dll

error[E0425]: cannot find value in module
--> src/dma/context/mod.rs:107:77
|
107 | batcher.read_into(pawn + cs2dumper::client::C_CSPlayerPawnBase::m_bIsScoped, &mut is_scoped);
| ^^^^^^^^^^^ not found in
|
help: consider importing this constant
|
1 + use crate::dma::cs2dumper::client::C_CSPlayerPawn::m_bIsScoped;
|
help: if you import , refer to it directly
|
107 - batcher.read_into(pawn + cs2dumper::client::C_CSPlayerPawnBase::m_bIsScoped, &mut is_scoped);
107 + batcher.read_into(pawn + m_bIsScoped, &mut is_scoped);
|m_bIsScopedcs2dumper::client::C_CSPlayerPawnBasecs2dumper::client::C_CSPlayerPawnBasem_bIsScoped

warning: unused import:
--> src/dma/context/mod.rs:2:5
|
2 | use crate::dma::cs2dumper::client::C_CSPlayerPawn::m_bIsScoped;
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: on by defaultcrate::dma::cs2dumper::client::C_CSPlayerPawn::m_bIsScoped#[warn(unused_imports)]

For more information about this error, try .
warning: (bin "radarflow") generated 1 warning
error: could not compile (bin "radarflow") due to 2 previous errors; 1 warning emittedrustc --explain E0425radarflowradarflow

**Comment by a2x** [comment]
That's not my project... Open an issue on that repo instead.

**Comment by qixu666777** [comment]
I used the offset you just updated, but when I compiled it, it prompted an offset error? Isn't it a problem with your deviation?
