### ISSUE TITLE
FOR THE LOVE OF GOD STOP CHANGING THE FUCKING SCHEMA HOLY CHRIST

### ISSUE THREAD

**Issue by 9xN** [a2x/cs2-dumper#134]

**Comment by M3351AN** [comment]
structure did not changed, missing schemas due to valve removed from cs2

**Comment by 9xN** [comment]
thats a lie its been at least 5 times also i realized shortly after the engine had a small rework

**Comment by M3351AN** [comment]
> thats a lie its been at least 5 times also i realized shortly after the engine had a small rework

dude mad for enemy sensor time?¿

**Comment by a2x** [comment]
The times inbetween after the branch merge were so small, I wouldn't even consider that.

**Comment by 9xN** [comment]
yea my glow hack that fetches offsets from this repo "broke" again and had people complaining in my dms non stop about it and since normally when that happens its just cause it takes forever for new offsets to appear in this repo or the structure entirely fucking changes and i have to rewrite a json parser at 3am so little kakavich can drink his vodka and play cs with his little wall see through cheats i figured thats what the issue was it was because `m_flDetectedByEnemySensorTime` was removed

**Comment by a2x** [comment]
I understand projects like yours rely on the generated files, so I usually try to restrict breaking changes. However, things are sometimes subject to change when doing large code rewrites, which was the case here and was needed, in my opinion.

I'm going to close this for now. Good luck with your project.

**Comment by 9xN** [comment]
thank you
