### ISSUE TITLE
can't seem to find m_flDetectedByEnemySensorTime ?

### ISSUE THREAD

**Issue by DAZstar** [a2x/cs2-dumper#135]
Also many netvars are not there in client

**Comment by M3351AN** [comment]
valve removed it

**Comment by Danjopeko23** [comment]
Also i cant find forcejump. Somebody help?

**Comment by a2x** [comment]
> Also i cant find forcejump. Somebody help? Is it renamed or smth?

https://github.com/a2x/cs2-dumper/blob/96b0942a476a3d2775dcda1127421e803d8a9244/output/buttons.hpp#L16

**Comment by a2x** [comment]
`m_flDetectedByEnemySensorTime` was removed in the latest update.
