### ISSUE TITLE
Dumper crashing

### ISSUE THREAD

**Issue by romancewastaken** [a2x/cs2-dumper#136]
I couldn't get the prebuilt executable to not crash or the one after building from source. I'm not very familiar with rust so I couldn't get any of the commands for version or anything to work for logging but yeah. Is the release out of date?

**Comment by a2x** [comment]
Is it actually crashing and not just not printing anything to stdout by default, which is intended?

Try to invoke the binary with the `-vvv` argument (e.g. `cs2-dumper.exe -vvv`). Do you see a "_finished in ...s_" message at the bottom, and do you see an output folder in the same directory?

**Comment by romancewastaken** [comment]
> Is it actually crashing and not just not printing anything to stdout by default, which is intended?
> 
> Try to invoke the binary with the `-vvv` argument (e.g. `cs2-dumper.exe -vvv`). Do you see a "_finished in ...s_" message at the bottom, and do you see an output folder in the same directory?

Oh.. sorry, I was use to the old version printing out. It is pretty confusing that the app just opens and closes. My apologies.
