### ISSUE TITLE
May I ask where this value   “EnemySensor” is that I can’t find it after updating?

### ISSUE THREAD

**Issue by dongyoxuan1514** [a2x/cs2-dumper#139]
May I ask where this value   “EnemySensor” is that I can’t find it after updating?

**Comment by DAZstar** [comment]
Valve removed it

**Comment by M3351AN** [comment]
chk closed issues before create a new one
already removed 2 updates before

**Comment by boyo3473** [comment]
> Valve removed it

oh thats sad
