### ISSUE TITLE
Other Matrix signatures

### ISSUE THREAD

**Issue by LittleQiu233** [a2x/cs2-dumper#141]
Some 3rd-platfarm has encrypted some matrix signatures，so couldu add more signatures to reach the offset？

**Comment by a2x** [comment]
Can you elaborate in more detail?

**Comment by LittleQiu233** [comment]
There are various pattern for matrix, but some AntiCheat will hook some pattern so that they wont be used to read

**Comment by TheWindWa1ker** [comment]
Sir,There is a third-party platform called 5eplay, and they have unique encryption,Can you take a look? Thank you very much.
Link is https://arena.5eplay.com/home?lang=english

**Comment by a2x** [comment]
The tool is supposed to be used without anti-cheats running as they can interfere. And I'm sorry, but I won't be downloading a third-party Chinese platform to explore this further.

**Comment by YYF6789** [comment]
same problem，have you solved？
