### ISSUE TITLE
Question, player coordinates

### ISSUE THREAD

**Issue by OmorOrNot** [a2x/cs2-dumper#148]
What offset name is for player x y and z? 

Sorry if im writing in the wrong place

**Comment by M3351AN** [comment]
Do you mean cartesian coordinates relative to the map?

**Comment by OmorOrNot** [comment]
I mean where the player is located

**Comment by OmorOrNot** [comment]
for ESP and stuff

**Comment by a2x** [comment]
You can use `m_vecAbsOrigin` from within `CGameSceneNode`.

https://github.com/a2x/cs2-dumper/blob/80724bf9714c769bfb6598023f5fc119eb8d63ba/output/client.dll.hpp#L6316C42-L6316C56
