### ISSUE TITLE
when i run ,

### ISSUE THREAD

**Issue by mAiRenAs** [a2x/cs2-dumper#153]

**Comment by romancewastaken** [comment]
> 22:31:44 [ERROR] unable to find pattern: dwWeaponC4 22:31:44 [ERROR] unable to find pattern: dwGameRules 22:31:44 [ERROR] unable to find pattern: dwLocalPlayerController 22:31:44 [ERROR] unable to find pattern: dwPlantedC4 22:31:44 [ERROR] unable to find pattern: dwCSGOInput 22:31:44 [ERROR] unable to find pattern: dwNetworkGameClient_getLocalPlayer Error: Other("unable to find schema system pattern")

with a 7gb update sig scanning probably broke, to be expected. he fixes it pretty quick though
