### ISSUE TITLE
Offsets are wrong

### ISSUE THREAD

**Issue by x3in** [a2x/cs2-dumper#154]
Lots of offsets in client.dll are incorrect. 

To name a few: 
Sanitized Player name is 0x630 not the 0x7* value
Bone Array
Health  
pGameSceneNode

Is probably much more broken than just those.

**Comment by x3in** [comment]
![image](https://github.com/a2x/cs2-dumper/assets/155085936/a15cf9be-2e7f-4abe-ba77-61a065673885)

**Comment by x3in** [comment]
![image](https://github.com/a2x/cs2-dumper/assets/155085936/eb9b33bb-b1a2-4813-8ae0-2d897af5355f)
Seems the entire pPlayerController structure is wrong. The 0x748 offset is entirely empty. And the sanitized name is now directly stored at the 0x640 offset.

**Comment by a2x** [comment]
Thanks for letting me know. I missed that some of the fields moved around in the schema related structures.

Could you let me know if all is fine now?

**Comment by x3in** [comment]
> Thanks for letting me know. I missed that some of the fields moved around in the schema related structures.
> 
> Could you let me know if all is fine now?

I don't think so. sanitized player name is now at 0x630 and I think CSPlayerPawn + 0x7EB is iHealth now. 
It looks like the structure is very off what it should be.

**Comment by a2x** [comment]
Ok. I've got a meeting in a few minutes, so I'll take a closer look afterwards.

**Comment by a2x** [comment]
There are no issues for me.

I can get health by reading local player pawn + 0x324 (m_iHealth) and player name by reading local player controller + 0x630 (m_iszPlayerName).

FYI, `m_sSanitizedPlayerName` is now at 0x740.

**Comment by y287869864** [comment]
BoneArray can not work normally

**Comment by x3in** [comment]
> There are no issues for me.
> 
> I can get health by reading local player pawn + 0x324 (m_iHealth) and player name by reading local player controller + 0x630 (m_iszPlayerName).
> 
> FYI, `m_sSanitizedPlayerName` is now at 0x740.

You are right about sanitized player name ptr, being at 0x740.
However reading PlayerPawn + 0x324 does not get m_iHealth. 
![image](https://github.com/a2x/cs2-dumper/assets/155085936/1c83bdba-aae6-4ebc-bd2a-dc0ea88bdb00)

**Comment by a2x** [comment]
```cpp
const auto local_player_pawn = process::read_memory<uint64_t>(client_base + 0x180DB18);
const auto health = process::read_memory<int32_t>(local_player_pawn + 0x324);

printf("health: %d\n", health);
```

https://github.com/a2x/cs2-dumper/blob/3f6c8940978c16ea9a92714437b53b2ed3ffbd65/output/client.dll.hpp#L5725

![image](https://github.com/a2x/cs2-dumper/assets/45197573/15977a1d-1b65-4734-867f-05ff950e8da3)

**Comment by y287869864** [comment]
`DWORD64 GameSceneNode = mem.ReadEx<DWORD64>(EntityPawnAddress+ m_pGameSceneNode);
this->BoneArrayAddress = mem.ReadEx<DWORD64>(GameSceneNode + m_fOverrideFogEnd);`

It has been working fine before
After updating, it no longer works

**Comment by x3in** [comment]
Weird, just dumped and recompiled and now 0x324 is working for me as well. Strange...

**Comment by x3in** [comment]
Only issue now is something changed with the bone array.

**Comment by cezacs1** [comment]
still not working with this offsets

**Comment by QQ3028828376** [comment]
What is the bone point offset?

**Comment by QQ3028828376** [comment]
Can the author update cs2-dumper.exe?
