### ISSUE TITLE
error: expected identifier, found `{`    --> src/dma/cs2dumper/engine2_mod.rs:300:22     | 300 |             pub mod  {     |                      ^ expected identifier  error[E0433]: failed to resolve: could not find `cs2_dumper` in `engine2_mod`   --> src/dma/cs2dumper/mod.rs:11:22    | 11 | pub use engine2_mod::cs2_dumper::schemas::engine2_dll as engine;    |                      ^^^^^^^^^^ could not find `cs2_dumper` in `engine2_mod`  For more information about this error, try `rustc --explain E0433`. The following warnings were emitted during compilation:

### ISSUE THREAD

**Issue by Coforgpaper** [a2x/cs2-dumper#156]
error: expected identifier, found `{`
   --> src/dma/cs2dumper/engine2_mod.rs:300:22
    |
300 |             pub mod  {
    |                      ^ expected identifier

error[E0433]: failed to resolve: could not find `cs2_dumper` in `engine2_mod`
  --> src/dma/cs2dumper/mod.rs:11:22
   |
11 | pub use engine2_mod::cs2_dumper::schemas::engine2_dll as engine;
   |                      ^^^^^^^^^^ could not find `cs2_dumper` in `engine2_mod`

For more information about this error, try `rustc --explain E0433`.
The following warnings were emitted during compilation:

**Comment by a2x** [comment]
Should be fixed.
