### ISSUE TITLE
wrong offsets

### ISSUE THREAD

**Issue by cezacs1** [a2x/cs2-dumper#158]
sorry if you're working on it right now, but offsets are still wrong even though it has been updated

**Comment by a2x** [comment]
Be more specific please... Which ones? Have you done debugging, etc?

**Comment by kWAYTV** [comment]
> Be more specific please... Which ones? Have you done debugging, etc?

GlobalVars not working 4 me

**Comment by Simass** [comment]
i cant manage to fix correct timing and view angles. guessing about dwViewMatrix dwViewAngles dwGlobalVars. Also did bones structure changed or no? My code after cs update all bones stucked in one place...

**Comment by dongyoxuan1514** [comment]
> 我无法设法修复正确的时间和视角。猜测 dwViewMatrix dwViewAngles dwGlobalVars。骨骼结构是否也发生了变化？我的代码在 cs 更新后，所有骨骼都卡在一个地方……

ME too

**Comment by cezacs1** [comment]
> Be more specific please... Which ones? Have you done debugging, etc?

GlobalVarsBase and bone offsets are wrong.
![SS 2024-05-24 172127](https://github.com/a2x/cs2-dumper/assets/93098721/a079f028-5885-467e-8b1e-b9c0c4025fd2)

**Comment by boyo3473** [comment]
same with view angles

**Comment by a2x** [comment]
The offsets are correct, the structures have just changed it seems.

**Comment by MaYecha** [comment]
cs2 updated again @a2x

**Comment by dongyoxuan1514** [comment]
> same with view angles

can u fixd ？ icanot

**Comment by banovers** [comment]
你能修复吗？ icanot
