### ISSUE TITLE
update client.dll.json

### ISSUE THREAD

**Issue by cucumber3432134** [a2x/cs2-dumper#160]
update client.dll.json

**Comment by cucumber3432134** [comment]
yeah most of .json didnt updated , please update it , thanks!

**Comment by a2x** [comment]
All of them are up to date?

**Comment by cucumber3432134** [comment]
https://prnt.sc/enyNSslUFSDk , are you sure about that?

**Comment by a2x** [comment]
That's simply because the timestamps change in the other files. Run the dumper and compare the newly generated file against the existing one using Diff Checker or something, and you will see no changes.
