### ISSUE TITLE
Global Vars Offset

### ISSUE THREAD

**Issue by TTakaTit** [a2x/cs2-dumper#162]
Can you add the offset of GlobalVar pls

**Comment by cycript** [comment]
https://github.com/a2x/cs2-dumper/blob/90e394ac13bd92ac04700f89e77540f8fcca21cd/output/offsets.hpp#L17

**Comment by TTakaTit** [comment]
> https://github.com/a2x/cs2-dumper/blob/90e394ac13bd92ac04700f89e77540f8fcca21cd/output/offsets.hpp#L17

I mean this one, I think mine is old, or it will be old at some time.
![image](https://github.com/a2x/cs2-dumper/assets/122241065/8f0faaa3-714f-4846-8fe1-904987903aa4)
