### ISSUE TITLE
Checking for updates

### ISSUE THREAD

**Issue by Forsnoy** [a2x/cs2-dumper#170]
Hello, I would like to know where you parse information about the release of an update in cs2? I tried the steam api where there is a client version but it is not ideal, I would be grateful if you could share the method. Thank you in advance.

**Comment by a2x** [comment]
I don't. It's done manually at the moment, but this is something I've actually been meaning to look into.

You could take a look at how [SteamDB](https://github.com/SteamDatabase/GameTracking#readme) does it, I guess. I can't really give any more advice at the moment, sorry.
