### ISSUE TITLE
use of *offsetname*?

### ISSUE THREAD

**Issue by eboyfriends** [a2x/cs2-dumper#173]
quick question for use on offsets i havent been able to find anything on.

    constexpr std::ptrdiff_t dwPrediction = 0x181A850;
    constexpr std::ptrdiff_t dwEngineViewData = 0x5ECBFC;
    constexpr std::ptrdiff_t dwNetworkGameClient_isBackgroundMap = 0x281477;
    constexpr std::ptrdiff_t dwSoundService = 0x5ECB60;

**Comment by a2x** [comment]
1. `dwPrediction` is a pointer to the `CPrediction` class.
2. `dwEngineViewData` was added by [this](https://github.com/a2x/cs2-dumper/pull/142) pull request.
3. `dwNetworkGameClient_isBackgroundMap` is used internally within the `CEngineClient::IsInGame` function.
4. `dwSoundService` is a pointer to the `CSoundService` class (see above pull request).
