### ISSUE TITLE
is view angles offset fixed yet it has been not working for a long time now dont tell me it works when it does not

### ISSUE THREAD

**Issue by boyo3473** [a2x/cs2-dumper#175]
:)

**Comment by M3351AN** [comment]
wdym "it has been not working for a long time now"
the truth is it works
if u failed to get the value, only reason is code skill issue
![5de83e28786cbf268a016d4be8d25bf6](https://github.com/a2x/cs2-dumper/assets/65479796/5be50d82-0ff9-4061-a559-0a15a36c526d)

**Comment by M3351AN** [comment]
imaging dude wanna get viewangles
Vector3 viewAngles = VARS::memRead<Vector3>(VARS::baseAddress + offsets::dwViewAngles);

uintptr_t baseAddress = GetModuleBaseAddress(processId, L"client.dll");

**Comment by boyo3473** [comment]
> wdym "it has been not working for a long time now" the truth is it works if u failed to get the value, only reason is code skill issue ![5de83e28786cbf268a016d4be8d25bf6](https://private-user-images.githubusercontent.com/65479796/339843794-5be50d82-0ff9-4061-a559-0a15a36c526d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzOTAzMjcsIm5iZiI6MTcxODM5MDAyNywicGF0aCI6Ii82NTQ3OTc5Ni8zMzk4NDM3OTQtNWJlNTBkODItMGZmOS00MDYxLWE1NTktMGExNWEzNmM1MjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDE4MzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmOTA3MjAxNzc4YjcyYmQzMDQ2NzliOGMyZjZjNWU2NGJkYTg3M2VmZTU1NDYzZDE2OWZlMzEwY2QyOWZmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QK1PljGo7HneOHW8pHJ9-uWVq35rc8poIEGLozhfm14)

last time i used it i cant write to it when it used to work its only the cpp ones c# is working fine
