### ISSUE TITLE
c9a253) error[E0425]: cannot find value `dwGameEntitySystem_getHighestEntityIndex` in module `cs2dumper::offsets::client_dll`    --> src/dma/threaddata/mod.rs:181:91     | 181 | ...lient_dll::dwGameEntitySystem_getHighestEntityIndex as u64).into();     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `dwGameEntitySystem_highestEntityIndex`     |    ::: src/dma[表情]2dumper/offsets_mod.rs:13:13     | 13  | ...   pub const dwGameEntitySystem_highestEntityIndex: usize = 0x1510;     |       ---------------------------------------------------------------- similarly named constant `dwGameEntitySystem_highestEntityIndex` defined here  For more information about this error, try `rustc --explain E0425`. The following warnings were emitted during compilation:

### ISSUE THREAD

**Issue by Coforgpaper** [a2x/cs2-dumper#176]
c9a253)
error[E0425]: cannot find value `dwGameEntitySystem_getHighestEntityIndex` in module `cs2dumper::offsets::client_dll`
   --> src/dma/threaddata/mod.rs:181:91
    |
181 | ...lient_dll::dwGameEntitySystem_getHighestEntityIndex as u64).into();
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `dwGameEntitySystem_highestEntityIndex`
    |
   ::: src/dma[表情]2dumper/offsets_mod.rs:13:13
    |
13  | ...   pub const dwGameEntitySystem_highestEntityIndex: usize = 0x1510;
    |       ---------------------------------------------------------------- similarly named constant `dwGameEntitySystem_highestEntityIndex` defined here

For more information about this error, try `rustc --explain E0425`.
The following warnings were emitted during compilation:
![e92e7ee195e7fb94956dcf6149961bc2](https://github.com/a2x/cs2-dumper/assets/163156194/ebb3b611-1ae6-4907-9321-5e754a97a888)

**Comment by M3351AN** [comment]
stop paste until u can understand those code
`dwGameEntitySystem_getHighestEntityIndex` exists nowhere
since sth named `dwGameEntitySystem_highestEntityIndex`

**Comment by M3351AN** [comment]
imaging CHINAMAN knows only ctrl+v but cannot read english
![3480c0c87325d39f2067dbae0c250598](https://github.com/a2x/cs2-dumper/assets/65479796/f98c5ee4-a17d-4bfb-a9ef-44669182634e)
