### ISSUE TITLE
dwViewMatrix is a potentially wrong offset.

### ISSUE THREAD

**Issue by Luma-arch** [a2x/cs2-dumper#185]
When trying to read the viewmatrix for my project, before, it read perfectly, so i went on to see if the adress was wrong. 
I found 2 of  them which could be the potential ViewMatrix Offset.

I first found the one that a2x dumper automatically dumped. which is:
client.dll+1A1FDB0
when i went to confirm if the values were correct i took a look and found this:
![imagen](https://github.com/a2x/cs2-dumper/assets/172939309/aa23cbc0-4e8a-4b7f-ab09-a8203d1b3d41)
as you can see in the image the matrix is missing a number, when moving my camera the 16 values should change.
Also the value which is below the one that doesnt change shouldn't change only by increment or decrements of 0.01 .2 , etc...
And when doing a manual scan to find the offset, i found a very convicing one which didn't work for me, (maybe the viewmatrix is read differently now?) but i found the offset: 
client.dll + 1A204E0
![imagen](https://github.com/a2x/cs2-dumper/assets/172939309/8ccb92cf-a657-4e73-b4f6-ecbf9f92cbe9)
As you can see, now it looks more like a 4x4 matrix because all 16 values move. 

a2x if i am dumb and do not know how to read the viewmatrix offset because im rusty af please let me know how its read.

**Comment by a2x** [comment]
It is a 4x4 matrix (four rows, four columns) so read it as that. `0x1A1FDB0` is also correct.

![image](https://github.com/a2x/cs2-dumper/assets/45197573/30f92acc-31c6-4299-b781-2ca2c5bd7497)

**Comment by Luma-arch** [comment]
OK, thank you, figured it out myself.
