### ISSUE TITLE
some problem with dwGameTypes_mapName

### ISSUE THREAD

**Issue by meanwhiletothestars** [a2x/cs2-dumper#188]
"matchmaking.dll": {
    "dwGameTypes_mapName": 288}
for some reason - wrong offset 

i cant read mapname past 2 updates

**Comment by a2x** [comment]
Seems it's now at `0x120` ] `0x4`. Maybe best to just read it from global vars + `0x1B8`.

![image](https://github.com/a2x/cs2-dumper/assets/45197573/9cf1ec55-8988-4f30-94bf-658054b2441a)

**Comment by meanwhiletothestars** [comment]
Thanks!
