### ISSUE TITLE
wrong offsets?

### ISSUE THREAD

**Issue by 8pmX8** [a2x/cs2-dumper#19]
some offsets dont work, i dont know if its my code but 

                localEntity.addy = CS2.ReadPointer(Client, Offs.dwLocalPlayerPawn);
                IntPtr controller = CS2.ReadPointer(localEntity.addy, 0x1654);
                Console.WriteLine(CS2.ReadInt(controller, 0x7C8));

this for exemple does not work, printing controller does work but that always returns 0 when it shouldnt

**Comment by 8pmX8** [comment]
might be the memory hook im using, any good ones?

**Comment by lintangtimur** [comment]
hi bro, do u know how to get address of this class `C_BaseEntity`?
my purpose just want to print value from m_iHealth, the logic is baseAddr + C_BaseEntity add + offset right?

**Comment by 8pmX8** [comment]
should be i havent used c# or c++ for cheating in a while, but no i dont get how to get the local player entity, you could try going through the entity list to find the corresponding entity

**Comment by lintangtimur** [comment]
So, this repository primarily only provides offset information, right? Do we need to find the pointer address for the class being used ourselves, like when using CE?

**Comment by 8pmX8** [comment]
so, basically you get everything off it, if you get an offset from client.dll IN THE OFFSETS.CS or HPP, thats the first address, and then you can get its class and find it to get offsets usable after it, and that goes on infinitly

Client (with it being defined ofc) + offsetinoffsetsfile
