### ISSUE TITLE
ERRORS on execution

### ISSUE THREAD

**Issue by Zhanytrix** [a2x/cs2-dumper#190]
```cs2-dumper.exe -c pcileech -a device=fpga```

 [ERROR] unable to find plugin with name 'pcileech'.
 [ERROR] possible available `Connector` plugins are:
 [ERROR] outdated/mismatched `Connector` plugins where found at:
Error: Memflow(Error(Inventory, PluginNotFound))

```cs2-dumper.exe -a device=fpga``` or ```cs2-dumper.exe``` or ```cs2-dumper.exe ... -p cs2.exe```
Error: Memflow(Error(OsLayer, ProcessNotFound))

**Comment by a2x** [comment]
If you aren't trying to use a pcileech supported DMA device, just run the executable without passing any arguments. Otherwise, make sure you installed the connector properly (check out the memflow repo on how to do so).

**Comment by Zhanytrix** [comment]
The issue was that the command is with `:` and not with `=`.

I solved running:
```cs2-dumper.exe -a device:fpga```
