### ISSUE TITLE
Outputs rust files as client.dll.rs making it unable to import easily

### ISSUE THREAD

**Issue by conner-replogle** [a2x/cs2-dumper#194]
What i said in title is this a feature im confused

**Comment by a2x** [comment]
Yes, I agree that it should be simpler. It would be nice to have a separate crate available that streamlines the process.

**Comment by conner-replogle** [comment]
Could we make that a config toggle? I can implement that. Also would be nice to setup the crates as a Binary and a Library. In order to make it so that we can call the library from other rust code so signatures can be gathered on start of a program. While the binary is a wrapper that just calls the library.

**Comment by a2x** [comment]
Now, the generated Rust files no longer have a `.` in the file name before the extension (which was why they couldn't be imported).

For standalone Rust projects, it might better to use my other project instead (to avoid adding unnecessary complexity to this code base). It also doesn't require the game to be running.

https://github.com/a2x/cs2-analyzer
