### ISSUE TITLE
External Aimbot offsets

### ISSUE THREAD

**Issue by DEFS9** [a2x/cs2-dumper#198]
I'm pretty sure that the new offsets are outdated (for aimbot only) esp offsets work fine!

Can you confirm? because my Aimbot isn't aiming at all.
Possibly the viewmatrix or spotted offset?

**Comment by a2x** [comment]
No, I think it must be an issue with your code. Please do some debugging first.

**Comment by Scr1pterLua** [comment]
Yea that’s a skill issue pal fix ur code before making a issue LMAO

**Comment by Scr1pterLua** [comment]
My Aimbot works fine and I’m using the same GitHub
