### ISSUE TITLE
dwGlobalVarsvar

### ISSUE THREAD

**Issue by AirJM** [a2x/cs2-dumper#199]
Hi,

I've been working with the cs2-dumper project, and I noticed that the offset 0x1B8 in the address dwGlobalVarsvar + 0x1B8 is used to read the map name. However, I couldn't find this specific offset in the client_dll.json file.

Could you please add the dwGlobalVarsvar variable to the offsets in your project? It would be very helpful for my work.

Thank you for your great project and your assistance!

**Comment by nyrilol** [comment]
are you good? please take a look at offsets.hpp lmao

**Comment by AirJM** [comment]
> are you good? please take a look at offsets.hpp lmao你好吗？请查看 offsets.hpp lmao

Hi,

I noticed that the offset for dwGlobalVars is available in offsets.hpp, but the sub-offsets within GlobalVars are not shown in clientdll.hpp. For example, dwGameRules is listed in offsets.hpp, and in clientdll.hpp we have sub-addresses under GameRules namespace C_CSGameRules such as m_bGameRestart which indicates whether the game has restarted.

I would like to know if there are any sub-offsets for dwGlobalVars in clientdll.hpp that can provide the MapName variable.

I might be missing something as I am new to reverse engineering, but I appreciate your help and thank you for the great project.

**Comment by dxshie** [comment]
you could literally open cs take the offset open ce attach and jump to the address and look at the struct yourself and take as a reference the csgo global vars struct which is widly available in a lot of repos.
you might be able to use a schema dumper where im not sure if the globalvars are dumped there as well

**Comment by AirJM** [comment]
> you could literally open cs take the offset open ce attach and jump to the address and look at the struct yourself and take as a reference the csgo global vars struct which is widly available in a lot of repos.你可以从字面上打开 CS，获取偏移量，打开 CE，附加并跳转到地址，自己查看结构体，并以 CSGO 全局变量结构体作为参考，该结构体在很多存储库中都很容易获得。 you might be able to use a schema dumper where im not sure if the globalvars are dumped there as well您可能可以使用架构转储器，我不确定 Globalvar 是否也在那里转储
> 
> edit: your map name should exist at 0x180 or 0x188编辑：您的地图名称应存在于0x180或0x188

Thank you for clarifying my doubts. I really appreciate your help, which has allowed me to take another step forward in my learning journey.
