### ISSUE TITLE
Dump interfaces in OLEACC.dll crash

### ISSUE THREAD

**Issue by sysrom** [a2x/cs2-dumper#2]
OS Windows10 22H2 19045.3448
Rustc:rustc 1.72.0 (5680fa18f 2023-08-23)
Cargo:cargo 1.72.0 (103a7ff2e 2023-08-15)
Gameversion CS2 2000142/13948
debug with Visual Studio Code&rust-analyzer plugin

2023-09-28T07:14:18.810Z INFO  [cs2_dumper::dumpers::interfaces] Dumping interfaces in OLEACC.dll...
module.rs line 123 let function_ordinal = *ordinal_table.offset(i as isize);
Unhandled exception at 0x00007FF69D521963 in cs2-dumper.exe: 0xC0000005: Access violation reading location 0x0000024787E3B380.

**Comment by a2x** [comment]
I was unable to reproduce the issue, but can you confirm if 8af8c4856bd356c8fde2619bf86d1830d17d13ef fixed it for you?

**Comment by sysrom** [comment]
thanks for fixing!
