### ISSUE TITLE
Outdated pattern for deltatick as of 8/8

### ISSUE THREAD

**Issue by Luma-arch** [a2x/cs2-dumper#203]
The pattern for dwNetworkGameClient_deltaTick is outdated.
Log: 

23:12:28 [INFO] found 16 buttons
23:12:29 [INFO] found 132 interfaces across 35 modules
23:12:31 [ERROR] outdated pattern: dwNetworkGameClient_deltaTick
23:12:31 [INFO] found 32 offsets across 5 modules
23:12:32 [INFO] found 2329 classes and 342 enums across 17 modules
23:12:32 [INFO] analysis completed in 3.571333 seconds

will still dump but its not included

**Comment by HH333** [comment]
dwGameTypes_mapName: usize = 0x120;

**Comment by a2x** [comment]
Download the latest release.
