### ISSUE TITLE
Does not dump dwViewAngles

### ISSUE THREAD

**Issue by Skwrr** [a2x/cs2-dumper#209]
It can dump everything on every file, but dwViewAngles is missing in offsets.json

**Comment by Skwrr** [comment]
This is due dwCSGOInput not being found (#208 )

**Comment by Luma-arch** [comment]
heres viewangles offset, thank me later. " 0x19D2E48"

**Comment by Luma-arch** [comment]
constexpr std::ptrdiff_t dwViewAngles = 0x19D2E48; if you want c + p

**Comment by LauraSavall** [comment]
For people even more lazy
[offsets.json](https://github.com/user-attachments/files/16619603/offsets.json)

**Comment by Skwrr** [comment]
thanks, I was trying to figure out how to build a rust app for too long and I was getting desperate lmao

> heres viewangles offset, thank me later. " 0x19D2E48"

**Comment by Luma-arch** [comment]
Anyone knows if it is dumping correctly?

**Comment by Skwrr** [comment]
i'll check my cheat rn

**Comment by Skwrr** [comment]
working fine for me, except buttons.json because dwCSGOInput has to dump it

**Comment by Skwrr** [comment]
i'll try to build #210 and send the exe here

**Comment by Luma-arch** [comment]
Designer name and m_pentity changed, that was my problem

**Comment by LauraSavall** [comment]
> working fine for me, except buttons.json because dwCSGOInput has to dump it

I confirm TriggerBot is dead for now

**Comment by Skwrr** [comment]
> Designer name and m_pentity changed, that was my problem

i think they are dumper correctly, i dont use those offsets on my external

**Comment by Luma-arch** [comment]
> > working fine for me, except buttons.json because dwCSGOInput has to dump it
> 
> I confirm TriggerBot is dead for now

you could use mouse_event or sendinput, works just as well, for more security if you are using kernel driver implement mouse click

**Comment by Skwrr** [comment]
> > > working fine for me, except buttons.json because dwCSGOInput has to dump it
> > 
> > 
> > I confirm TriggerBot is dead for now
> 
> you could use mouse_event or sendinput, works just as well, for more security if you are using kernel driver implement mouse click

i use mouse_event for trigger and it isnt working either

**Comment by Skwrr** [comment]
> i'll try to build #210 and send the exe here

it still says outdated dwCSGOInput

**Comment by Luma-arch** [comment]
Entitylist or something is broken, bones are not being rendered on any other pawn than my localplayer.

**Comment by LauraSavall** [comment]
> but RCS, AIM, trigger doesn't work which is weird

any update about this @Skwrr ?
