### ISSUE TITLE
offsets are incorrect

### ISSUE THREAD

**Issue by CowNowB** [a2x/cs2-dumper#215]
My cs2 project is using your repository as a dependency. Currently my project is not working at all, so I think your output is incorrect

**Comment by a2x** [comment]
Can you be more specific on what's not working?

**Comment by Guralol** [comment]
> 我的 cs2 项目正在使用您的存储库作为依赖项。目前我的项目根本没有工作，所以我认为你的输出是不正确的
Yes,AimStar doesn't seem to work，both the old version and the last,but offsets seems to be correct

**Comment by CowNowB** [comment]
> Can you be more specific on what's not working?

My project loads by directly getting the offsets in your repository, the versions prior to this CS2 update are available. After this update, I still directly get the offsets of your repository, but none of them work anymore, like ESP, aimbot, etc.. Some people even caused the game to crash because of continuous writing of NoFlash to the wrong address.

**Comment by MaYecha** [comment]
> > Can you be more specific on what's not working?
> 
> My project loads by directly getting the offsets in your repository, the versions prior to this CS2 update are available. After this update, I still directly get the offsets of your repository, but none of them work anymore, like ESP, aimbot, etc.. Some people even caused the game to crash because of continuous writing of NoFlash to the wrong address.

I often use AIMSTAR and I am glad to see the original author here
I have made modifications to your warehouse, and all functions are working properly
![image](https://github.com/user-attachments/assets/8c3a2a05-3b67-4c8c-a654-c03237a0dad5)

**Comment by CowNowB** [comment]
> I often use AIMSTAR and I am glad to see the original author here I have made modifications to your warehouse, and all functions are working properly

@MaYecha Can you make a pull request?

**Comment by MaYecha** [comment]
> > I often use AIMSTAR and I am glad to see the original author here I have made modifications to your warehouse, 和 all functions are working properly
> 
> @MaYecha Can you make a pull request?

Okay, I did it, but I'm not sure if it's my problem
If I use AIMSTAR source code 4.6.3, all weapons' self aiming can work normally without turning on AIMLOCK
But I used the latest source code and made modifications to make it work, but the self aiming of the handgun won't work unless I turn on AIMLOCK, and the rifle doesn't need it

**Comment by MaYecha** [comment]
> > I often use AIMSTAR and I am glad to see the original author here I have made modifications to your warehouse, 和 all functions are working properly
> 
> @MaYecha Can you make a pull request?

[pull request](https://github.com/CowNowB/Aimstar/pull/8/commits)

**Comment by MaYecha** [comment]
> > I often use AIMSTAR and I am glad to see the original author here I have made modifications to your warehouse, 和 all functions are working properly
> 
> @MaYecha Can you make a pull request?

[](url)

**Comment by CowNowB** [comment]
> > > I often use AIMSTAR and I am glad to see the original author here I have made modifications to your warehouse, 和 all functions are working properly
> > 
> > 
> > @MaYecha Can you make a pull request?
> 
> [pull request](https://github.com/CowNowB/Aimstar/pull/8/commits)

Thank you
