### ISSUE TITLE
outdated offsets.

### ISSUE THREAD

**Issue by Luma-arch** [a2x/cs2-dumper#220]

**Comment by LauraSavall** [comment]
I confirm...

**Comment by a2x** [comment]
Did the game update?

**Comment by LauraSavall** [comment]
https://github.com/a2x/cs2-dumper/releases/tag/0.1.2

**Comment by LauraSavall** [comment]
> Did the game update?

I guess, I had to dump it myself

**Comment by afafontes** [comment]
> Did the game update?

yeah, game updated few mins ago

**Comment by a2x** [comment]
Can someone make a pr then? I won't be home for quite a few hours.

**Comment by LauraSavall** [comment]
https://github.com/a2x/cs2-dumper/pull/221 @a2x

**Comment by a2x** [comment]
> https://github.com/a2x/cs2-dumper/pull/221 @a2x 

Thanks
