### ISSUE TITLE
NEW UPDATE NANI????

### ISSUE THREAD

**Issue by Scr1pterLua** [a2x/cs2-dumper#222]

**Comment by LauraSavall** [comment]
Again ??

**Comment by LauraSavall** [comment]
I use them..which are the one I PR

[offsets.json](https://github.com/user-attachments/files/16684006/offsets.json)
[buttons.json](https://github.com/user-attachments/files/16684007/buttons.json)
[client.dll.json](https://github.com/user-attachments/files/16684008/client.dll.json)

**Comment by lwnb666777** [comment]
I used offsets.hpp and client.hpp, I used a2x to update yesterday, and it worked very well, and today I used your update, and some features are invalid

**Comment by lwnb666777** [comment]
Then I'll just wait for the a2x update.... @a2x

**Comment by LauraSavall** [comment]
> Then I'll just wait for the a2x update.... @a2x

I'm actually playing..and it's working...
![image](https://github.com/user-attachments/assets/51a94267-385a-4ccb-9db9-e3e6c09d18e4)

**Comment by LauraSavall** [comment]
You can dump them yourself BTW :
1) Download dumper : [here](https://github.com/a2x/cs2-dumper/releases/tag/0.1.2)
2) Open CS2
3) Run dumper
4) Folder "output" will be created along cs2-dumper.exe... take files needed

**Comment by lwnb666777** [comment]
> > I used offsets.hpp and client.hpp, I used a2x to update yesterday, and it worked very well, and today I used your update, and some features are invalid
> 
> https://github.com/a2x/cs2-dumper/blob/36946e7af2580f3f98738650ba3d83cc27b398f7/output/client_dll.hpp#L2
> 
> https://github.com/a2x/cs2-dumper/blob/36946e7af2580f3f98738650ba3d83cc27b398f7/output/offsets.hpp#L2

That's what I'm using, and some of the features don't work
