### ISSUE TITLE
Failed to find pattern error afer 10/18/2023 update

### ISSUE THREAD

**Issue by SandFoxy** [a2x/cs2-dumper#23]
ERROR [cs2_dumper::dumpers::offsets] Failed to find pattern for dwForceAttack2.
ERROR [cs2_dumper::dumpers::offsets] Failed to find pattern for dwPlantedC4.

**Comment by alwaysolohere** [comment]
same trouble

**Comment by a2x** [comment]
Replace the config.json file with the latest one. I accidentally forgot to.
