### ISSUE TITLE
Could this cause VAC?

### ISSUE THREAD

**Issue by JannesBonk** [a2x/cs2-dumper#237]
I've been using this dumper on my external on start up to get the offsets, and I'm wondering if it could trigger VAC.

**Comment by M3351AN** [comment]
afaik, [memflow-native](https://github.com/memflow/memflow-native) open process to rpm, and may cause vac fragged.
for me, only dump with -insecure once the game updated, instead of dump at eachtime the chit startup

**Comment by JannesBonk** [comment]
> afaik, [memflow-native](https://github.com/memflow/memflow-native) open process to execute rpm, and may cause vac / low trust factor.
> for me, only dump with -insecure once the game updated, instead of dump at eachtime the chit startup

Indeed it does, I'll see what I can do related to that. I was thinking of making the dumper directly in the cheat, as it's not that hard.

**Comment by a2x** [comment]
> afaik, [memflow-native](https://github.com/memflow/memflow-native) open process to execute rpm, and may cause vac / low trust factor. for me, only dump with -insecure once the game updated, instead of dump at eachtime the chit startup

Basically this unless you are using a different connector.
