### ISSUE TITLE
only thing that happens if a cmd flashing

### ISSUE THREAD

**Issue by tabbli4** [a2x/cs2-dumper#238]
genuinely pissed myself, you sure this isnt a rat?

**Comment by a2x** [comment]
That’s the intended behavior, and it will still create an output directory. Alternatively, you can enable verbose logging by passing the -v flag when running it. Also, the code is open-source, so even if you’re concerned about the release binary being unsafe (I can assure you it’s not), you can compile it yourself.

**Comment by tabbli4** [comment]
alright thanks, i thought it had a ui for it but thanks!:D
