### ISSUE TITLE
Unable to find plugin with name 'pcileech'

### ISSUE THREAD

**Issue by kauanF7** [a2x/cs2-dumper#248]
I am facing this error when I run "cs2-dumper.exe -f cs -c pcileech". Do you know what it could be?
![image](https://github.com/user-attachments/assets/0d5a84d7-93ff-43ba-beb5-2a53e78696a4)

**Comment by a2x** [comment]
Looks like you haven't installed the pcileech connector. Take a look at the memflow-pcileech repo for instructions on how to do so.
