### ISSUE TITLE
EntityList offset is wrong

### ISSUE THREAD

**Issue by Luma-dot** [a2x/cs2-dumper#254]
For some reason the Entitylist offset is not working when doing entitylist + 0x10 listentry is invalid, and when taking a look at the structure in reclass it doesnt have a order similar to what ive seen before, seems traversing the entitylist is different now, or offset is wrong.

**Comment by a2x** [comment]
Looks right to me.

![image](https://github.com/user-attachments/assets/3fd5a6e8-dbd7-4034-839d-2985e2b0817f)

**Comment by Luma-dot** [comment]
Then why is entitylist reading 0? my memory class is completely fine as reading something else is working, tf.

**Comment by Luma-dot** [comment]
> Owner

Nevermind, my driver for some reason didn't catch an Exception in a __try SEH block and crashed my driver, after remapping it it didnt work for some reason, tf is wrong with windows

**Comment by Dz6k** [comment]
Add 0x4 to the Entity List value while the dumper doesn't update :)
