### ISSUE TITLE
Can you update the update linux offset?

### ISSUE THREAD

**Issue by Nianmou** [a2x/cs2-dumper#267]
I'm getting an error with cargo test -- --nocapture

**Comment by Nianmou** [comment]
`root@ECS8468:/mnt/steam/cs2/cs2-dumper# cargo test --bin cs2-dumper
warning: multiple variants are never constructed
  --> src/source2/schema_system/schema_type.rs:7:5
   |
6  | pub enum SchemaAtomicCategory {
   |          -------------------- variants in this enum
7  |     Basic = 0,
   |     ^^^^^
8  |     T,
   |     ^
9  |     CollectionOfT,
   |     ^^^^^^^^^^^^^
10 |     TF,
   |     ^^
11 |     TT,
   |     ^^
12 |     TTF,
   |     ^^^
13 |     I,
   |     ^
14 |     None,
   |     ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: multiple variants are never constructed
  --> src/source2/schema_system/schema_type.rs:19:5
   |
18 | pub enum SchemaTypeCategory {
   |          ------------------ variants in this enum
19 |     BuiltIn = 0,
   |     ^^^^^^^
20 |     Ptr,
   |     ^^^
21 |     Bitfield,
   |     ^^^^^^^^
22 |     FixedArray,
   |     ^^^^^^^^^^
23 |     Atomic,
   |     ^^^^^^
24 |     DeclaredClass,
   |     ^^^^^^^^^^^^^
25 |     DeclaredEnum,
   |     ^^^^^^^^^^^^
26 |     None,
   |     ^^^^

warning: multiple fields are never read
  --> src/source2/schema_system/schema_type.rs:88:9
   |
87 | pub union SchemaTypeUnion {
   |           --------------- fields in this union
88 |     pub schema_type: Pointer64<SchemaType>,
   |         ^^^^^^^^^^^
89 |     pub class_binding: Pointer64<SchemaClassBinding>,
   |         ^^^^^^^^^^^^^
90 |     pub enum_binding: Pointer64<SchemaEnumBinding>,
   |         ^^^^^^^^^^^^
91 |     pub array: SchemaArrayT,
   |         ^^^^^
92 |     pub atomic: SchemaAtomicT,
   |         ^^^^^^
93 |     pub atomic_tt: SchemaAtomicTT,
   |         ^^^^^^^^^
94 |     pub atomic_tf: SchemaAtomicTF,
   |         ^^^^^^^^^
95 |     pub atomic_ttf: SchemaAtomicTTF,
   |         ^^^^^^^^^^
96 |     pub atomic_i: SchemaAtomicI,
   |         ^^^^^^^^

warning: variants `None`, `Fast`, and `Slow` are never constructed
 --> src/source2/tier1/utl_memory_pool.rs:5:5
  |
4 | pub enum MemoryPoolGrowType {
  |          ------------------ variants in this enum
5 |     None = 0,
  |     ^^^^
6 |     Fast,
  |     ^^^^
7 |     Slow,
  |     ^^^^

warning: method `block_size` is never used
  --> src/source2/tier1/utl_ts_hash.rs:53:12
   |
42 | / impl<D, const C: usize, K> UtlTsHash<D, C, K>
43 | | where
44 | |     D: Pod + PointerExt,
45 | |     K: Pod,
   | |___________- method in this implementation
...
53 |       pub fn block_size(&self) -> i32 {
   |              ^^^^^^^^^^

warning: `cs2-dumper` (bin "cs2-dumper" test) generated 5 warnings
    Finished `test` profile [optimized + debuginfo] target(s) in 0.13s
     Running unittests src/main.rs (target/debug/deps/cs2_dumper-b23d66e86ce730ec)

running 5 tests
test analysis::offsets::tests::global_vars ... FAILED
test analysis::offsets::tests::build_number ... FAILED
test analysis::offsets::tests::local_player_controller ... FAILED
test analysis::offsets::tests::local_player_pawn ... FAILED
test analysis::offsets::tests::window_size ... FAILED

failures:

---- analysis::offsets::tests::global_vars stdout ----
Error: Memflow(Error(OsLayer, ModuleNotFound))

---- analysis::offsets::tests::build_number stdout ----
thread 'analysis::offsets::tests::build_number' panicked at src/analysis/offsets.rs:147:73:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- analysis::offsets::tests::local_player_controller stdout ----
Error: Memflow(Error(OsLayer, ModuleNotFound))

---- analysis::offsets::tests::local_player_pawn stdout ----
Error: Memflow(Error(OsLayer, ModuleNotFound))

---- analysis::offsets::tests::window_size stdout ----
thread 'analysis::offsets::tests::window_size' panicked at src/analysis/offsets.rs:251:86:
called `Option::unwrap()` on a `None` value


failures:
    analysis::offsets::tests::build_number
    analysis::offsets::tests::global_vars
    analysis::offsets::tests::local_player_controller
    analysis::offsets::tests::local_player_pawn
    analysis::offsets::tests::window_size

test result: FAILED. 0 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass `--bin cs2-dumper`
`
He got this error and couldn't find the reason for it

**Comment by a2x** [comment]
Closing as duplicate.
