### ISSUE TITLE
Using Help

### ISSUE THREAD

**Issue by shoval-dev** [a2x/cs2-dumper#268]
I am a beginner and don't know how to use your program. I downloaded and deployed the Rust Nightly version and related toolchain according to the Rust website. I also downloaded and installed memflow. i successfully compiled your cs2-dump project, but i don't know how to use it. this FPGA device is required. Forgive me, I've searched a lot of places and I can't get an answer!
<img width="587" alt="bec2236bf9de7045e0a29bc7a8b671d" src="https://github.com/user-attachments/assets/8d75393a-7954-45a4-bcc7-021d39b335ef">

**Comment by dxshie** [comment]
do you even use a pcileech / FPGA ?

**Comment by Nianmou** [comment]
> do you even use a pcileech / FPGA ?你甚至使用 pcileech / FPGA 吗？

Does linux need an FPGA as a device to use cs2-dumper?

**Comment by shoval-dev** [comment]
> do you even use a pcileech / FPGA ?

No, I just want to dump the data to a file. So I'm asking how this should be used

**Comment by dxshie** [comment]
you're using the wrong connector then use the correct connector for your desired way to read memory of your target for instance the native connector

**Comment by dxshie** [comment]
> > do you even use a pcileech / FPGA ?你甚至使用 pcileech / FPGA 吗？
> 
> Does linux need an FPGA as a device to use cs2-dumper?

no you guys should look up what a connector is within memflow and what FPGA pcileech means if you would know that you'd be able to answer those questions yourself

**Comment by Nianmou** [comment]
![Snipaste_2024-11-04_08-02-15](https://github.com/user-attachments/assets/a80a8328-f605-43b2-8d32-96eade328591)
Installed native

**Comment by Nianmou** [comment]
> you're using the wrong connector then use the correct connector for your desired way to read memory of your target for instance the native connector

![Snipaste_2024-11-04_07-54-05](https://github.com/user-attachments/assets/57fcda3a-496c-46dd-a315-fe4eea645013)
![Snipaste_2024-11-04_07-54-31](https://github.com/user-attachments/assets/cf9fc940-2188-4819-b1e5-cbde8b4edf57)
He just said he couldn't find the connectors and that I had already used memflowup to install them

**Comment by a2x** [comment]
Can you please confirm whether you're trying to use the linux branch or if you're trying to use the pcileech connector targeting the windows version of the game.

**Comment by shoval-dev** [comment]
> Can you please confirm whether you're trying to use the linux branch or if you're trying to use the pcileech connector targeting the windows version of the game.

I used the latest version of the current main branch because you said you fixed the build for Linux. Do I have to use the Linux branch, but the version I compiled seems to be too far from the current main branch's functionality, and I'm not sure how to use it

**Comment by a2x** [comment]
> > Can you please confirm whether you're trying to use the linux branch or if you're trying to use the pcileech connector targeting the windows version of the game.
> 
> 
> 
> I used the latest version of the current main branch because you said you fixed the build for Linux. Do I have to use the Linux branch, but the version I compiled seems to be too far from the current main branch's functionality, and I'm not sure how to use it

If you're targeting the Linux version of CS2, use the Linux branch. If you are targeting the Windows version of CS2, use the main branch.

Note that the Linux branch is currently outdated and will likely not work without updating the patterns, etc. This is something I can't fix at the moment as I don't even have an active Linux installation and it's something that I never planed to support from the beginning. It only exists due to a PR made by someone else.

To clear up any confusion, the main branch is compilable on Linux because you can use certain memflow connectors to read the memory of the target windows machine, meaning that you can run the executable on Linux instead of on the windows machine while the game is running. For example: If you have a DMA card that connects from your windows PC to your other Linux PC, you can install the memflow-pcileech connector on the Linux PC and that would allow you read the memory of the windows machine so that cs2-dumper could be ran on the Linux machine instead. The same can be said for other memflow connectors apart from memflow-native which will only work on the same platform. On windows, this will just call ReadProcessMemory and the alternative on Linux.

Hopefully this somewhat makes sense.

**Comment by shoval-dev** [comment]
> > > Can you please confirm whether you're trying to use the linux branch or if you're trying to use the pcileech connector targeting the windows version of the game.
> > 
> > 
> > I used the latest version of the current main branch because you said you fixed the build for Linux. Do I have to use the Linux branch, but the version I compiled seems to be too far from the current main branch's functionality, and I'm not sure how to use it
> 
> If you're targeting the Linux version of CS2, use the Linux branch. If you are targeting the Windows version of CS2, use the main branch.
> 
> Note that the Linux branch is currently outdated and will likely not work without updating the patterns, etc. This is something I can't fix at the moment as I don't even have an active Linux installation and it's something that I never planed to support from the beginning. It only exists due to a PR made by someone else.
> 
> To clear up any confusion, the main branch is compilable on Linux because you can use certain memflow connectors to read the memory of the target windows machine, meaning that you can run the executable on Linux instead of on the windows machine while the game is running. For example: If you have a DMA card that connects from your windows PC to your other Linux PC, you can install the memflow-pcileech connector on the Linux PC and that would allow you read the memory of the windows machine so that cs2-dumper could be ran on the Linux machine instead. The same can be said for other memflow connectors apart from memflow-native which will only work on the same platform. On windows, this will just call ReadProcessMemory and the alternative on Linux.
> 
> Hopefully this somewhat makes sense.

Thank you very much for your guidance. I don't have a DMA card, so I was wondering if I could create a QEMU VM under Windows and then read the CS2 process information under the QEMU VM. Please forgive me, I am just a noob. Thanks again for your guidance!

**Comment by a2x** [comment]
Yes, please see:
https://github.com/memflow/memflow-qemu

**Comment by Isaac-Duarte** [comment]
This new list_addr signature should work.

let list_addr = signature!("48 83 3D ? ? ? ? ? 0F 95 C0 C3")

Though I am missing 

13:25:26 [ERROR] unable to find signature for: dwNetworkGameClient_deltaTick
13:25:27 [ERROR] unable to find signature for: dwGameRules
13:25:27 [ERROR] unable to find signature for: dwGlobalVars
13:25:27 [ERROR] unable to find signature for: dwViewMatrix

Should be good enough for most things
