### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by externalkji** [a2x/cs2-dumper#27]
Is there a pointer already to the game entity system if so, how would I use it and which name does it have?
second question: is there anything like it was in csgo the PlayerResource pointer or something maybe it gameplayerresource now?

I ask because I try to filter the entities ingame but as of now I can iterate them but sometimes they dont show because I may fail to differeciate between them

**Comment by a2x** [comment]
https://github.com/a2x/cs2-dumper/blob/256f9f5f1246ff51e5a873c414c33c9b73c54f3b/generated/offsets.hpp#L21
