### ISSUE TITLE
能够像

### ISSUE THREAD

**Issue by 769687520** [a2x/cs2-dumper#3]
Can it be as comprehensive as a hazedeumper? There are many missing points

**Comment by VilotStar** [comment]
Not exactly sure what you mean by this, but I see this as better than haze as everything is properly grouped into files and namespaces/structs

**Comment by 769687520** [comment]
> 不太确定你的意思，但我认为这比雾霾更好，因为所有内容都正确分组到文件和名称空间/结构中

I haven't found dwClientState, maybe I'm too stupid

**Comment by VilotStar** [comment]
I will admit the naming is a bit weird in this dumper, and not the same as other naming conventions.
I believe the offset you are looking for is C_CSPlayerPawnBase::m_iPlayerState

**Comment by chiteroman** [comment]
> I haven't found dwClientState, maybe I'm too stupid

I'm searching it too

**Comment by VilotStar** [comment]
Doesn't clientState have a ptr to localPlayerController?

**Comment by chiteroman** [comment]
> Doesn't clientState have a ptr to localPlayerController?

Idk

**Comment by 769687520** [comment]
The changes are really significant. Moving forward, backward, left, right, and moving like CSGO, you can't find it at all

**Comment by a2x** [comment]
Closing for now. Feel free to open another issue with more information.
