### ISSUE TITLE
Strange error 0x8007012B

### ISSUE THREAD

**Issue by bphucc** [a2x/cs2-dumper#32]
Hi, I downloaded via Release and running the game while trying to dump the offsets, but I encountered this error: 
![image](https://github.com/a2x/cs2-dumper/assets/42881433/7a417823-9bac-435b-9e44-4ffdc85f85ab)
Then the _Generated_ folder is created but nothing in there, I also tried _--verbose_, as well as run the program as Admin rights, but no use, any idea?

**Comment by a2x** [comment]
Hi, thanks for opening an issue.

In your terminal, please run `set RUST_BACKTRACE=full` and then download and run [this](https://github.com/a2x/cs2-dumper/files/13255478/cs2-dumper.zip) binary (which contains debug symbols) then paste the full backtrace here.

**Comment by bphucc** [comment]
Here is the trace:
![image](https://github.com/a2x/cs2-dumper/assets/42881433/5fa8e20f-8ac8-4206-867a-d2849f93c67b)

**Comment by a2x** [comment]
As I said, I need you to use the binary I just provided [here](https://github.com/a2x/cs2-dumper/files/13255478/cs2-dumper.zip) since it contains debug symbols.

**Comment by bphucc** [comment]
Sorry my bad :D, here are the traces from the build above:
![image](https://github.com/a2x/cs2-dumper/assets/42881433/22842c75-361a-4614-98fc-f656c00a3476)

**Comment by a2x** [comment]
Ah, it seems you also need the PDB. In this case, it's best if you can build the project yourself.

1. Install Rust from [here](https://www.rust-lang.org/tools/install) if you haven't already.
2. Open up a terminal in the project root and run `cargo build` - This should create a `target/debug` directory. Don't forget to copy the `config.json` file there too.
3. Then, in that directory, again run `set RUST_BACKTRACE=full` before running the binary.

This should give you a much more detailed stack trace, as the one you've provided isn't useful. Then, I can look into the issue.

Thanks

**Comment by bphucc** [comment]
Hi @a2x, thanks for your detailed reply, I compiled and tested myself, here are the traces:
![image](https://github.com/a2x/cs2-dumper/assets/42881433/743b1f7e-6d4c-4155-985e-07c08947cf0a)

**Comment by a2x** [comment]
Can you tell me if the latest commit resolved this for you?

**Comment by bphucc** [comment]
Yes, It does the job now, thanks for your effort helping me, I'm really grateful 🥇 

![image](https://github.com/a2x/cs2-dumper/assets/42881433/bc6ea0a7-8afe-4eb5-8201-26d68388ccb2)
