### ISSUE TITLE
m_vecOrigin is wrong

### ISSUE THREAD

**Issue by DanTheEpicMan** [a2x/cs2-dumper#39]
I might be doing something wrong but currently it says m_vecOrigin is 0x80 when using this, just returns 0 from the read memory, the only thing that works for me is an old offset for it, 0x1224. Maybe its just an issue with my game in so way, like an update wasn't pushed but IDK.

**Comment by a2x** [comment]
It's an issue with your code. Take a look at [this](https://github.com/a2x/cs2-dumper/blob/614c15299e32119739322397e135d608976fc994/src/dumper/offsets.rs#L313) example.
