### ISSUE TITLE
What about Linux version of the game offsets?

### ISSUE THREAD

**Issue by hamad12a** [a2x/cs2-dumper#4]
Is it possible to push the offsets concerning Linux OS?

**Comment by a2x** [comment]
I probably won't add support for Linux, but I'm open to pull requests.

**Comment by hamad12a** [comment]
Idk; I hope I could it myself

**Comment by VilotStar** [comment]
You can just use a library to read and scan memory pretty easily that allows cross-platform. Or impl the reading yourself then replace it in this project

**Comment by hamad12a** [comment]
> You can just use a library to read and scan memory pretty easily that allows cross-platform. Or impl the reading yourself then replace it in this project

I have all the necessary tools on my distro but I don't know how to find those offsets; i.e., which memory regions I have to search for. If you at least provide some guidelines I'd appreciate it.

**Comment by b1scoito** [comment]
> How hard is it to implement proper linux support?

All that is needed to do is implement read/write for linux e.g using `process_vm_readv` and `process_vm_writev`, in this case, only read is used and change the config for patterns for the respective Linux game libraries. At least from what I've seen these are the only changes needed. I'm looking forward to make a PR in the near feature implementing cross-platform support for the dumper.
