### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by zijingsh** [a2x/cs2-dumper#40]
hello i build exe，next run error
Running `target\debug\cs2-dumper.exe`
Error: invalid utf-8 sequence of 1 bytes from index 0
error: process didn't exit successfully: `target\debug\cs2-dumper.exe` (exit code: 1)
PS D:\cs2-dumper-main>

**Comment by a2x** [comment]
Please provide the full stack trace. You can get this by running `set RUST_BACKTRACE=full` in your terminal before running the binary.

**Comment by zijingsh** [comment]
PS D:\cs2-dumper-main> set RUST_BACKTRACE=full  
PS D:\cs2-dumper-main> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target\debug\cs2-dumper.exe`
Error: invalid utf-8 sequence of 1 bytes from index 0
error: process didn't exit successfully: `target\debug\cs2-dumper.exe` (exit code: 1)
PS D:\cs2-dumper-main> 

I don't know much about the rust programming language

This error only exists in the Chinese system. I think it is caused by gbk coding, but I don't know how to correct it
