### ISSUE TITLE
No offsets.hpp generator when ran.

### ISSUE THREAD

**Issue by TrippleAWap** [a2x/cs2-dumper#42]
The pre-generated files has an offsets.hpp but when I it myself and try getting it it doesnt generate one, am I doing something wrong?

**Comment by TrippleAWap** [comment]
After running the test these are the errors.
![image](https://github.com/a2x/cs2-dumper/assets/90356816/9c837eab-50ad-4a6d-aad2-04c4b1dcbfc0)

**Comment by a2x** [comment]
Please make sure you're in-game first.

**Comment by TrippleAWap** [comment]
https://github.com/a2x/cs2-dumper/assets/90356816/f47185b5-2d23-40d6-b317-f8a266993bb1

**Comment by a2x** [comment]
Do you have the `config.json` file in the same directory?

**Comment by TrippleAWap** [comment]
as?

**Comment by TrippleAWap** [comment]
o wait... that was why mb
