### ISSUE TITLE
spotted by mask

### ISSUE THREAD

**Issue by cyberstyl** [a2x/cs2-dumper#5]
spotted by mask offset is most likely wrong

**Comment by ZanderFoster** [comment]
SpottedByMask has its own additional offset. Use ctrl+f and seach "spotted" I believe the offset is 0x8 for bSpotted and 0xC for bSpottedByMask

**Comment by cyberstyl** [comment]
> bSpotted has its own additional offset. Use ctrl+f and seach "spotted" I believe the offset is 0x8 for bSpotted and 0xC for bSpottedByMask
> 
> Should look something like this: pPlayerPawn + SpottedOffset + SpottedByMaskOffset





https://imgur.com/V2frr3M
https://imgur.com/91buzAC
doesnt help
