### ISSUE TITLE
exposing a crate

### ISSUE THREAD

**Issue by MrAliSalehi** [a2x/cs2-dumper#52]
Hi, thank you for creating this library, could you please expose a crate out of this so it can be used inside other programs? specifically the `dump_offsets` and `utils::Process` ..etc, the exposed `dump` function can have a custom `Buffer` which can be either a `Directory` to dump everything inside it or some memory chunk that could be later be used by the `client-side` code, I could help with that part anyways but that requires you to expose a crate first.
again, thank you <3.

**Comment by a2x** [comment]
I may do this at a later time.
