### ISSUE TITLE
Question regarding offsets (MouseEnable)

### ISSUE THREAD

**Issue by externalkji** [a2x/cs2-dumper#53]
In CS:GO there were offsets which would indicate if the mouse is enabled due to beeing in console, buymenu and stuff.
Are these also found in CS2? If so, would you be so kind and add them to the dumper please?

private val cursorEnableAddress = clientDLL.address + ClientOffsets.dwMouseEnable
private val cursorEnablePtr = clientDLL.address + ClientOffsets.dwMouseEnablePtr 

If they are not there, would it be possible to check for buymenu and stuff in an external way?

**Comment by a2x** [comment]
The `cl_mouseenable` command is no longer present in CS2, and I don't believe there's a direct equivalent.

You can check if the buy menu is open by reading the value of [this](https://github.com/a2x/cs2-dumper/blob/273ff417177dcc49b7f0d1028625c4c494db4813/generated/client.dll.hpp#L1972) offset. For checking whether the console is open externally, I would start with CE. Unfortunately, I don't have the time/effort to look into this.
