### ISSUE TITLE
Possible PDB generator?

### ISSUE THREAD

**Issue by RealPacket** [a2x/cs2-dumper#58]
Although I don't have any copy of CS2 around me, I think that it would be easier if the dumper could also generate PDBs.
I have no experience with the PDB format, but that might change.

IDA would ask you for a PDB and you'd provide the auto-generated PDB.
You could also make it generate an IDAPython script which renames everything for you (which is more likely to do).

**Comment by a2x** [comment]
I'm sorry, but I don't know what the use for this is when most of the information in the generated files is dumped at runtime. If I were to expand this project to dump RTTI as well, I could see a use case then, but right now, could you please clarify?

**Comment by RealPacket** [comment]
when you open a binary like client.dll, IDA asks you for a PDB, you could provide a PDB generated by this and IDA would use it to rename symbols, this means that you'd not have to manually rename by jumping to offsets and instead it would all be automatic.
This means it would be more effortless to reverse engineer the game.

**Comment by a2x** [comment]
Yes, I understand, but my point is that in Source 2, the core of the Schema System is defined in a separate module named schemasystem.dll, which basically maps out and describes most of the game's classes, fields, types, etc. This module is already well-documented (i.e. [here](https://praydog.com/reverse-engineering/2015/06/24/source2.html)), so generating a PDB file for renaming is unnecessary. Therefore, apart from renaming offsets as defined in the config.json file, I don't see any other reason currently for a PDB generator, so I wanted to clarify your intentions.

**Comment by RealPacket** [comment]
yes, but **IDA doesn't know anything about `schemasystem.dll` and how to get the names using it**, so **when you're looking at `client.dll`** you **won't** see the names of anything that `schemasystem.dll` provides,
this means (again) that you will have to jump all over the place in the binary to rename them,
providing a PDB (or generating a IDAPython script that
renames everything for you) is way better than going through every variable and renaming it in IDA

**Comment by RealPacket** [comment]
ok
