### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Omega172** [a2x/cs2-dumper#6]
These are some small changes that i would really like

Give type information of the dumped NetVars/Schemas.
Some Examples:
       m_pWeaponServices       = 0x968(CPlayer_WeaponServices*)
       m_pMovementServices   = 0x9A8(CPlayer_MovementServices*)
       v_angle                           = 0x9B8(QAngle)
       m_iHideHUD                   = 0x9D4(uint32)

Add another optional arg to get rid of the timestamps useing println! instead of !log::info

**Comment by a2x** [comment]
Thanks, added in 6d04af2758b0f6cc7243c786a05e0cac2997cecd

For printing verbose messages, you can now pass the `-v` or `--verbose` flag.
