### ISSUE TITLE
Some offsets are invalid

### ISSUE THREAD

**Issue by Coslly** [a2x/cs2-dumper#63]
m_pClippingWeapon, dwViewMatrix
I only found these two there could be more...

**Comment by a2x** [comment]
I've just had a brief look and those both seem to be correct. Are you sure your problem isn't elsewhere?

**Comment by swpq** [comment]
> m_pClippingWeapon, dwViewMatrix I only found these two there could be more...
works fine for me but ight gang

**Comment by IHutuXian** [comment]
Have u updated config.txt? Additionally, I found that the dumper downloaded directly from the release did not successfully obtain a new offset, even if config.txt was updated.
