### ISSUE TITLE
Error: Only part of a ReadProcessMemory or WriteProcessMemory request was completed. (0x8007012B)

### ISSUE THREAD

**Issue by capelosini** [a2x/cs2-dumper#64]
This errors appears in the start and the program exit with code 1, this just starts to happens after the february 6th update

**Comment by capelosini** [comment]
The last commit of a2x solved [here](https://github.com/a2x/cs2-dumper/commit/d6a68b1ead88a0acd4b5382a574cf22e30e1a5fa), i think it was changes in some signatures and offsets, I think happens almost every game update.

**Comment by JeepEda** [comment]
i used dumper with new config.json but still have same error... sad...

**Comment by JeepEda** [comment]
I think the reason is that cs2 has a big update

**Comment by capelosini** [comment]
> I think the reason is that cs2 has a big update

Yes it has, there was some code changes in the dumper instead of just config changes, so sadly you may have to build and run the latest source code, I made it and i'm good now.

**Comment by JeepEda** [comment]
just build lastest source code?

**Comment by capelosini** [comment]
> just build lastest source code?

Yes, just clone the repository and run the rust code
