### ISSUE TITLE
can not running

### ISSUE THREAD

**Issue by IDhammaI** [a2x/cs2-dumper#69]
![image](https://github.com/a2x/cs2-dumper/assets/124808841/6b63ed95-35a5-402b-b804-015bd14a504f)

**Comment by a2x** [comment]
What is your OS locale? Could you try using Powershell and changing the default character encoding to UTF-8 (See [this](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.3#changing-the-default-encoding)), then try running the program from there?

**Comment by a2x** [comment]
Closed due to inactivity.
