### ISSUE TITLE
New offsets…

### ISSUE THREAD

**Issue by Suspectxyzz** [a2x/cs2-dumper#70]
Hello, if you can add the offset for 'mapnameval', it is for maps, thank you.
I did not find this offset in your list.

**Comment by a2x** [comment]
Are you sure you're not referring to [this](https://github.com/a2x/cs2-dumper/blob/cd30a731df074381a484affc639f03a89cc207dd/src/dumper/offsets.rs#L310)?

**Comment by gaoyuxiang120** [comment]
> Are you sure you're not referring to [this](https://github.com/a2x/cs2-dumper/blob/cd30a731df074381a484affc639f03a89cc207dd/src/dumper/offsets.rs#L310)?

hello, i have same question. it would be very helpful if you can add the mapNameVal in somewhere we can find after updates.

**Comment by capta9n** [comment]
> Are you sure you're not referring to [this](https://github.com/a2x/cs2-dumper/blob/cd30a731df074381a484affc639f03a89cc207dd/src/dumper/offsets.rs#L310)?

this is indeed not the correct offset

**Comment by a2x** [comment]
I don't know what offset you're referring to then.

**Comment by Suspectxyzz** [comment]
> I don't know what field you're referring to then.

https://github.com/Suspectxyzz/CS2_DMA_Radar_py/blob/main/app.py#L74
from this one is

**Comment by a2x** [comment]
Added in d267a60b7da889cda4db6c47386520a47fd48272
You can now find it [here](https://github.com/a2x/cs2-dumper/blob/d267a60b7da889cda4db6c47386520a47fd48272/generated/offsets.hpp#L57).
