### ISSUE TITLE
<Enhancement> Add Memflow (pcileech)

### ISSUE THREAD

**Issue by huntergregal** [a2x/cs2-dumper#73]
First - thank you for sharing this awesome project. 

I wanted to bring up the idea of integrating https://github.com/memflow/memflow for the dumper. Ideally one could select a connector to use such as https://github.com/memflow/memflow-pcileech

This would allow dumping offsets totally externally - in the event CS2Dumper becomes a VAC target.

**Comment by a2x** [comment]
Closing this as soon the project will be migrated to use https://github.com/a2x/cs2-analyzer instead (which can work entirely without the game running).

This will also (hopefully) allow for automatically updating the repo with the latest offsets, etc., after each game update.
