### ISSUE TITLE
Wrong Offsets generated

### ISSUE THREAD

**Issue by PhilCode-creator** [a2x/cs2-dumper#74]
Im Using the newest version off the dumper and too my Knowledge there was no update since then,
I tried using the m_IHealth offset which it dumped as: 0x334 when after trying too get it manually (working) is 0x7F0

maby thats just me or is the dumper not working correctly / was there an update

(attachments: client.dll.hpp)

[client.txt](https://github.com/a2x/cs2-dumper/files/14323084/client.txt)

**Comment by PhilCode-creator** [comment]
same goes with the player flags

**Comment by a2x** [comment]
Show how you're reading them.

**Comment by PhilCode-creator** [comment]
im using this class to read: https://github.com/manuroger112/memory/blob/main/memory.h and code is: 
```
#include "memory.h"
#include <thread>
#include <iostream>

namespace offset {
	constexpr std::ptrdiff_t m_iPawnArmor = 0x7F4; // int32_t
	constexpr std::ptrdiff_t m_iPawnHealth = 0x7F0; // uint32_t
	constexpr std::ptrdiff_t dwForceJump = 0x17226E0;
	constexpr std::ptrdiff_t m_fFlags = 0x3D4; // uint32_t

}

int main() {
	while (true)
	{
		std::this_thread::sleep_for(std::chrono::milliseconds(100));

		const uintptr_t localPlayer = VARS::memRead<uintptr_t>(VARS::baseAddress + 0x19038F8);
		const uint32_t armor = VARS::memRead<uint32_t>(localPlayer + offset::m_iPawnArmor);

		int health = VARS::memRead<int>(localPlayer + offset::m_iPawnHealth);	
		if (!localPlayer)
			continue;

		int32_t m_fFlags = VARS::memRead<int32_t>(localPlayer + offset::m_fFlags);
		if (GetAsyncKeyState(VK_SPACE) && m_fFlags & (1 << 0)) {
			VARS::memWrite(VARS::baseAddress + offset::dwForceJump, 65537);
			std::this_thread::sleep_for(std::chrono::milliseconds(2));
			VARS::memWrite(VARS::baseAddress + offset::dwForceJump, 256);
		}
	}

	return 0;
}
```

**Comment by PhilCode-creator** [comment]
btw I fixed the part with the health the changed the name but for the flags still

**Comment by a2x** [comment]
Your issue is that you are reading the flags on the controller instead of the pawn.

https://github.com/a2x/cs2-dumper/blob/d267a60b7da889cda4db6c47386520a47fd48272/generated/offsets.hpp#L27
