### ISSUE TITLE
Still can find the offsets

### ISSUE THREAD

**Issue by TasteMyR99** [a2x/cs2-dumper#8]
idk if im doing something wrong but i did what you said, i opened the `generated` folder and searched for `offset` but find nothing

**Comment by VilotStar** [comment]
In the `generated` folder, there are the files;
`offsets.cs`, `offsets.hpp`, `offsets.json`, `offsets.rs`
These contain the offsets you are looking for most likely

**Comment by TasteMyR99** [comment]
i can send you a screenshot there is are no offset files in my `generated` folder

**Comment by TasteMyR99** [comment]
![image](https://github.com/a2x/cs2-dumper/assets/146031738/871b872a-78c9-40e1-b465-7f76dbf47bf2)

**Comment by VilotStar** [comment]
Don't search using windows explorer, you will always have a bad experience with it
Select a file in the folder, then click the 'o' key until you see the explorer highlight the offsets.* file

**Comment by TasteMyR99** [comment]
i did that too, no offset files

**Comment by VilotStar** [comment]
[offsets.json](https://github.com/a2x/cs2-dumper/blob/main/generated/offsets.json)
I can find it in the repo perfectly fine, its possible your dump failed or got interrupted

**Comment by TasteMyR99** [comment]
how do i dump the files properly? join a lobby and run the dumper or what?

**Comment by VilotStar** [comment]
You can just run it on the home screen, shouldn't matter

**Comment by TasteMyR99** [comment]
now it worked, thanks man

**Comment by TasteMyR99** [comment]
ty
