### ISSUE TITLE
 Missing of dwClientState offset.

### ISSUE THREAD

**Issue by Mayuresh2112** [a2x/cs2-dumper#80]
Can I get offset for viewAngles from clientState for CS2( Counter-Strike 2) OR Can I get offset for ClientState for cs2?
 
 Missing of dwClientState offset.

**Comment by a2x** [comment]
`CClientState` isn't present in CS2 afaik (which runs Source 2 instead of CS:GO's Source 1 engine).

If you're external, just read view angles from `CCSGOInput`: `client.dll + 0x192D860`
