### ISSUE TITLE
Tooling and approach into finding the classes and methods

### ISSUE THREAD

**Issue by christianshub** [a2x/cs2-dumper#82]
@a2x, this is a really great tool, and beautifully made. Would you mind sharing your approach in extracting this information? What tooling are you using?

For example, how are you able to parse the exact classes and methods from the binaries? Take `m_ArmorValue` ([L2181](https://github.com/a2x/cs2-dumper/blob/7833227736608bd91db66372d0985236fb662f33/generated/client.dll.cs#L2181)) as an example. How do you know that method is also part of the class  `C_CSPlayerPawnBase` ([L2079](https://github.com/a2x/cs2-dumper/blob/7833227736608bd91db66372d0985236fb662f33/generated/client.dll.cs#L2079))?

```csharp
public static class C_CSPlayerPawnBase { // C_BasePlayerPawn
    public const nint m_pPingServices = 0x12C0; // CCSPlayer_PingServices*
    public const nint m_pViewModelServices = 0x12C8; // CPlayer_ViewModelServices*
    public const nint m_fRenderingClipPlane = 0x12D8; // float[4]
    // ...
    public const nint m_ArmorValue = 0x1570; // int32_t
    public const nint m_angEyeAngles = 0x1578; // QAngle
    // ...
}
```

It seems like a lot of information (strings, function names) is given when looking at `client.dll` through IDA, but I see no obvious way the classes and methods are tied together. Are you using a different tool than me, or is it just straight up obvious to you? lol 😄 

By searching for xrefs I find something that could look like a vtable, but to me there is still no obvious connection between the method `ArmorValue` and the class `C_CSPlayerPawnBase`.

I'd really like to contribute and help out in any way I can!

Best regards

**Comment by a2x** [comment]
Hi,

I recommend taking a look at this blog post: https://praydog.com/reverse-engineering/2015/06/24/source2.html

This should hopefully answer your questions.

Regards

**Comment by christianshub** [comment]
Thank you! <3
