### ISSUE TITLE
Where is client.dll?

### ISSUE THREAD

**Issue by ch3va** [a2x/cs2-dumper#83]
Where is client.dll?

**Comment by a2x** [comment]
Previously, files were generated in a different manner. Each module containing schema system registrations was written independently as a separate file. However, the current approach consolidates all modules into a single file (in this case, 'schemas.*'), where they are separated into different scopes.

See: https://github.com/a2x/cs2-dumper/blob/889ef7dcd85c745b20702627db7cf018cccb33b0/output/win/schemas.hpp#L3578
