### ISSUE TITLE
where is this ??

### ISSUE THREAD

**Issue by alsheikhaminulislam** [a2x/cs2-dumper#84]
where is this ??

m_iTeamNum
m_iGlowIndex

**Comment by a2x** [comment]
The current approach, at least for the time being, involves converting all field names and other identifiers to a specific code style for each language.

For instance:
- C++ header files are written using snake_case naming convention, where words are separated by underscores (e.g., field_name).
- C# files follow the PascalCase convention, where each word, including the first, starts with an uppercase letter (e.g., FieldName).
- Rust files employ a combination of snake_case for variables and functions (e.g., field_name) and UPPER_CAMEL_CASE for constants (e.g., CONSTANT_NAME).

With that being said, `m_iTeamNum` becomes `m_i_team_num`, which you can find here:
https://github.com/a2x/cs2-dumper/blob/889ef7dcd85c745b20702627db7cf018cccb33b0/output/win/schemas.hpp#L4451

`m_iGlowIndex`, on the other hand, was never present in this repository.

**Comment by alsheikhaminulislam** [comment]
Can you tell me what to do with glow manager if there is no glow index
