### ISSUE TITLE
Unable to parse

### ISSUE THREAD

**Issue by ch3va** [a2x/cs2-dumper#86]
Now it's becoming difficult to parse, can we go back to the previous format

**Comment by ch3va** [comment]
Completely unable to parse JSON

**Comment by arrayffs** [comment]
you might want to parse it using regular expressions, haven't tested it but it should work in theory

**Comment by a2x** [comment]
Fair point. I'll see what I can do.

**Comment by ch3va** [comment]
C_BaseEntity     |     m_iHealth     |     m_iHealth     |     820
C_BaseEntity     |     m_iTeamNum     |     m_iTeamNum     |     971
C_BasePlayerPawn     |     m_vOldOrigin     |          |     0
CEntityInstance     |     m_pEntity     |     m_pEntity     |     16
CEntityIdentity     |     m_designerName     |     m_designerName     |     32
CCSPlayerController     |     m_hPlayerPawn     |          |     0
C_CSPlayerPawnBase     |     m_vecLastClipCameraPos     |          |     0
C_CSPlayerPawn     |     m_aimPunchCache     |          |     0
C_CSPlayerPawnBase     |     m_iShotsFired     |          |     0
C_CSPlayerPawnBase     |     m_entitySpottedState     |          |     0
EntitySpottedState_t     |     m_bSpotted     |     m_bSpotted     |     8
EntitySpottedState_t     |     m_bSpottedByMask     |     m_bSpottedByMask     |     12
C_CSPlayerPawnBase     |     m_pClippingWeapon     |          |     0
CBasePlayerController     |     m_iszPlayerName     |     m_iszPlayerName     |     1592
C_BaseEntity     |     m_CBodyComponent     |     m_CBodyComponent     |     56
CBodyComponent     |     m_pSceneNode     |     m_pSceneNode     |     8
C_BaseEntity     |     m_pGameSceneNode     |     m_pGameSceneNode     |     792
CSkeletonInstance     |     m_modelState     |     m_modelState     |     352
CGameSceneNode     |     m_vecOrigin     |     m_vecOrigin     |     128
CGameSceneNode     |     m_vecAbsOrigin     |     m_vecAbsOrigin     |     200
CGameSceneNode     |     m_bDormant     |     m_bDormant     |     231
C_CSPlayerPawnBase     |     m_iIDEntIndex     |          |     0
C_CSPlayerPawnBase     |     m_angEyeAngles     |          |     0
C_BasePlayerPawn     |     m_pWeaponServices     |          |     0
CPlayer_WeaponServices     |     m_hMyWeapons     |     m_hMyWeapons     |     64
CCSWeaponBaseVData     |     m_szName     |          |     0
C_BaseEntity     |     m_nSubclassID     |     m_nSubclassID     |     864
C_EconItemView     |     m_iItemDefinitionIndex     |          |     0
C_AttributeContainer     |     m_Item     |     m_Item     |     80
C_EconEntity     |     m_AttributeManager     |          |     0
C_BaseModelEntity     |     m_vecViewOffset     |     m_vecViewOffset     |     3160
C_PlantedC4     |     m_flC4Blow     |          |     0
C_PlantedC4     |     m_bC4Activated     |          |     0
C_PlantedC4     |     m_bBombDefused     |          |     0

I can parse some, but there are still some parts that do not exist
I am using translation software

**Comment by ch3va** [comment]
Many names have changed

**Comment by arrayffs** [comment]
well everything changed, a lot of the offsets are missing which i assume will be added soon, i'd recommend you to just find the new offset names by just searching the values from the old version they haven't been changed yet and then just noting their new names

**Comment by ch3va** [comment]
I tried searching for values, but still couldn't find them

> 好吧，一切都变了，很多偏移量都丢失了，我认为很快就会添加，我建议您通过搜索尚未更改的旧版本中的值来找到新的偏移量名称，然后只记下它们的新名称



> 好吧，一切都变了，很多偏移量都丢失了，我认为很快就会添加，我建议您通过搜索尚未更改的旧版本中的值来找到新的偏移量名称，然后只记下它们的新名称

I tried searching for values, but still couldn't find them

**Comment by arrayffs** [comment]
yes, a lot of these offsets are missing at the moment, they will most likely be added very soon

**Comment by arrayffs** [comment]
I'll have a look if i can open a pull request with the list of the missing ones later on, mainly it seems that stuff around weapons and items is missing

**Comment by a2x** [comment]
> I'll have a look if i can open a pull request with the list of the missing ones later on, mainly it seems that stuff around weapons and items is missing

If you could, I'd be very grateful.

**Comment by a2x** [comment]
Should not longer be an issue.
