### ISSUE TITLE
Breaking Changes in the Latest Merge to Main Branch

### ISSUE THREAD

**Issue by a2x** [a2x/cs2-dumper#87]
In the recent merge of the `dev` branch into `main`, several breaking changes may impact some people relying on the generated files for inclusion in their projects.

**Most notably:**

### Code Style Conventions

Generated files now follow specific code style conventions depending on the programming language:

- **C++ header files:** Use `snake_case` naming convention, where words are separated by underscores (e.g., `field_name`).
- **C# files:** Follow the `PascalCase` convention, where each word, including the first, starts with an uppercase letter (e.g., `FieldName`).
- **Rust files:** Employ a combination of `snake_case` for variables and functions (e.g., `field_name`) and `UPPER_CAMEL_CASE` for constants (e.g., `CONSTANT_NAME`).

_// Edit: No longer applies to class, field or enum names._

### Consolidated Schema System Data

Previously, any module containing any schema-system registrations was written independently as a separate file, e.g., `client.dll.hpp`. The new approach consolidates all schema-system related data into a single file, E.g. `schema.hpp`. Within this file, modules are now separated into different scopes.
This change was _aimed_ at eventually making it easier to include the generated files in your project.

---

#### Current known issues:
- Empty comments are generated for certain fields.

---

**Please provide any suggestions for improvements below.**

**Comment by arrayffs** [comment]
for automatic parsing maybe try using regular expressions, another user said parsing the json file is not possible

**Comment by ch3va** [comment]
I can't find many offsets

**Comment by perisch04** [comment]
[OFFSETS] Could not find m_iPawnHealth
[OFFSETS] Could not find m_hPlayerPawn
[OFFSETS] Could not find m_sSanitizedPlayerName
[OFFSETS] Could not find m_vOldOrigin
[OFFSETS] Could not find m_bPawnIsAlive
[OFFSETS] Could not find m_bIsDefusing
[OFFSETS] Could not find m_pBulletServices
[OFFSETS] Could not find m_hObserverPawn
[OFFSETS] Could not find m_pObserverServices
[OFFSETS] Could not find m_pClippingWeapon
[OFFSETS] Could not find m_AttributeManager
[OFFSETS] Could not find m_iItemDefinitionIndex

logs from my offset grabber. Maybe some of those offsets exist just with different name.

**Comment by Suspectxyzz** [comment]
i need client.dll & offsets.json

**Comment by Suspectxyzz** [comment]
> > i need client.dll & offsets.json
> 
> I pushed the most recently generated files from the previous codebase to the [archive](https://github.com/a2x/cs2-dumper/tree/archive) branch.
thanks for the answer and will the `archive branch' always be updated....?

**Comment by cezacs1** [comment]
> > client.dll & offsets.json ihtiyacım var
> 
> En son oluşturulan dosyaları önceki kod tabanından [arşiv](https://github.com/a2x/cs2-dumper/tree/archive) dalına gönderdim.

this is better than the new system

**Comment by dcraig9123** [comment]
some offset names have been changed, why? ej, m_angEyeAngles, what is the new name?

**Comment by arrayffs** [comment]
> angEyeAngles, what is the new name?

read the readme

**Comment by romancewastaken** [comment]
this is a really bad update not going to lie. stuffing a bunch of files into one file and making it 20,445 lines was not the solution. what's going to happen is a big split, people using the old version of the dumper, and the new one. personally, i will be sticking with the old one.

**Comment by tishion** [comment]
good change, i prefer the new json schema.

**Comment by DareAngeL** [comment]
where to find : C_CSPlayerPawnBase - can't find it anymore.

**Comment by a2x** [comment]
> where to find : C_CSPlayerPawnBase - can't find it anymore.

Thanks for reporting. Seems like quite a few classes are currently missing. Am looking into it.

**Comment by a2x** [comment]
> this is a really bad update not going to lie. stuffing a bunch of files into one file and making it 20,445 lines was not the solution. what's going to happen is a big split, people using the old version of the dumper, and the new one. personally, i will be sticking with the old one.

I'm considering going back to the prior approach for this. However, doing this did have its reasons at the time.

Would like to know others thoughts.

**Comment by arrayffs** [comment]
might be a useless point but in my opinion hungarian annotation looks way better, idk if its just me but it feels just right

**Comment by jiggey1** [comment]
Worst thing you could have done in my opinion. Don't have access to the old tool either, archive branch will be outdated in less than a week, then i'm relying on good old UC. thanks a lot.

**Comment by dcraig9123** [comment]
> I'm considering going back to the prior approach for this. However, doing this did have its reasons at the time.
> 
> Would like to know others thoughts.

I think it is not a bad option but before making the change it is necessary to make sure that all the previous information appears correctly and now there are many cases and offsets that have been lost. Can you update the file with each update until the new version is correct?

**Comment by arrayffs** [comment]
> Worst thing you could have done in my opinion. Don't have access to the old tool either, archive branch will be outdated in less than a week, then i'm relying on good old UC. thanks a lot.

the stuff is still there just in different places, all you have to do is search up the new names.

**Comment by romancewastaken** [comment]
> Worst thing you could have done in my opinion. Don't have access to the old tool either, archive branch will be outdated in less than a week, then i'm relying on good old UC. thanks a lot.

if you need the old executable i can send it to you, sadly i deleted the actual source code though

**Comment by romancewastaken** [comment]
> > Worst thing you could have done in my opinion. Don't have access to the old tool either, archive branch will be outdated in less than a week, then i'm relying on good old UC. thanks a lot.
> 
> the stuff is still there just in different places, all you have to do is search up the new names.

"new names" the names of the offsets should of never changed, they should of had the same names and been in the same class's, if he does keep it this way there will be alot of UC posts with different named offsets and such.

**Comment by a2x** [comment]
> > > Worst thing you could have done in my opinion. Don't have access to the old tool either, archive branch will be outdated in less than a week, then i'm relying on good old UC. thanks a lot.
> > 
> > 
> > the stuff is still there just in different places, all you have to do is search up the new names.
> 
> "new names" the names of the offsets should of never changed, they should of had the same names and been in the same class's, if he does keep it this way there will be alot of UC posts with different named offsets and such.

I already undid that change.

Regarding schema file generation, I've now reverted to the previous method of creating a new file for each module. I'll push these changes shortly.

**Comment by romancewastaken** [comment]
> > > > Worst thing you could have done in my opinion. Don't have access to the old tool either, archive branch will be outdated in less than a week, then i'm relying on good old UC. thanks a lot.
> > > 
> > > 
> > > the stuff is still there just in different places, all you have to do is search up the new names.
> > 
> > 
> > "new names" the names of the offsets should of never changed, they should of had the same names and been in the same class's, if he does keep it this way there will be alot of UC posts with different named offsets and such.
> 
> I already undid that change.
> 
> Regarding schema file generation, I've now reverted to the previous method of creating a new file for each module. I'll push these changes shortly.

i think the best option would to be allow picking between the two, let the user pick if they want to generate new files or use the schema, at the end of the day its up to you though :)

**Comment by perisch04** [comment]
...
> i think the best option would to be allow picking between the two, let the user pick if they want to generate new files or use the schema, at the end of the day its up to you though :)
+1 to this even if i liked the old version more the updated one might be better for some users.

**Comment by a2x** [comment]
Thanks to everyone for your feedback.

I think this can be closed now, as all of the "controversial" changes have essentially been reverted.

If you have any new suggestions for improvements to the repo, please open a new issue. 👍
