### ISSUE TITLE
I can't find dwLocalPlayer anywhere...

### ISSUE THREAD

**Issue by MehPropy** [a2x/cs2-dumper#9]
Maybe I just didn't do something correctly, but I can't find dwLocalPlayer offset anywhere. Is it maybe supposed to be called something else?

**Comment by a2x** [comment]
https://github.com/a2x/cs2-dumper/blob/85e6224275f6f9f8c7f6b00ee33f5ffe260dd492/generated/offsets.hpp#L19

**Comment by MehPropy** [comment]
Thank you!
