### ISSUE TITLE
is  dwPlayerPawn == dwLocalPlayerPawn   then where is dwLocalPlayer ?

### ISSUE THREAD

**Issue by alsheikhaminulislam** [a2x/cs2-dumper#90]
is 
dwPlayerPawn == dwLocalPlayerPawn 

then where is dwLocalPlayer
?

**Comment by a2x** [comment]
What are you talking about?

**Comment by alsheikhaminulislam** [comment]
Actually I need these two parameters
![image](https://github.com/a2x/cs2-dumper/assets/62173570/68b8f059-a015-49fb-b382-1169ec9ecfa0)

**Comment by perisch04** [comment]
are you talking about m_hPlayerPawn?

**Comment by arrayffs** [comment]
dementia gaming $
