### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by V1ERA** [a2x/cs2-dumper#91]
the new update mess my autoupdater how can i bring the old offsets and client.dll back? can i have the old release ?

**Comment by a2x** [comment]
Hi, unfortunately, I no longer have the old binary file. For now, you can use the generated files from the old binary on the [archive](https://github.com/a2x/cs2-dumper/tree/archive) branch, but note that it won't be updated in the future.

However, it should be trivial to make your code work with the latest version of the repo.

**Comment by Trixxen** [comment]
yes the update sucks man sorry broke my autoupdate too
