### ISSUE TITLE
Can't find the dwForceJump offset.

### ISSUE THREAD

**Issue by itzgodcode** [a2x/cs2-dumper#92]
Hello, i was looking for dwForceJump in offsets.hpp but i can't find it anymore after the update. Where it is now?

**Comment by a2x** [comment]
There are newly generated button files, such as [buttons.hpp](https://github.com/a2x/cs2-dumper/blob/main/output/win/buttons.hpp), that now contain all of the key buttons, including force attack. However, the names have changed, so `dwForceAttack` is now just `attack`.

**Comment by itzgodcode** [comment]
Understood, but i cant figure it out how to get the offset with the method im using.

Example for "m_fFlags"
SCHEMA(std::int32_t, m_fFlags, "C_BaseEntity->m_fFlags");

then i use it as
int32_t flags = Globals::m_pLocalPlayerPawn->m_fFlags();

m_pLocalPlayerPawn is a pointer to a class where i have the SCHEMA stuff.

**Comment by itzgodcode** [comment]
@a2x can u help?

**Comment by a2x** [comment]
I don't understand what your issue is or what codebase you're magically working on.

Please provide me with more info and ensure your question is related to this repo in particular.

**Comment by itzgodcode** [comment]
im working with this base, here you have examples of my codebase
https://github.com/Exlodium/CS2-External-Base

**Comment by a2x** [comment]
Why did you not open an issue there instead?
