### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by Forsnoy** [a2x/cs2-dumper#93]
Hello, haven't been here for a long time, where did config.json go? Where can I get signatures now?

**Comment by a2x** [comment]
I removed it in favour of being able to use the pattern scanner from the pelite crate.

They're defined here now: https://github.com/a2x/cs2-dumper/blob/main/src%2Fanalysis%2Foffsets.rs#L71

**Comment by zijingsh** [comment]
now  is not show   dwForceAttack ？

**Comment by BXLESKY** [comment]
my client.dll.cs has nothing in it HELP!

**Comment by Trixxen** [comment]
this update sucks man
