### ISSUE TITLE
buildNumber

### ISSUE THREAD

**Issue by romancewastaken** [a2x/cs2-dumper#94]
Hello, was buildNumber forgotten about? I often used offsets.json in my API and used buildNumber in the game_info class but that appears to be missing. There is the class called engine2.dll with a dwBuildNumber but that's a bit different.

**Comment by a2x** [comment]
No.

The offset for dwBuildNumber is [here](https://github.com/a2x/cs2-dumper/blob/3a935f5d73ae0ce8299ffe444da44a3596027ea2/output/offsets.hpp#L31), and there is now a new file that gets generated named `info.json` that contains the actual build number and allows for easy parsing.
