### ISSUE TITLE
Dude please switch back or provide the old version of the dumper my hack is aids now because of this we loved the old way of the dumper and now you have ruined it.

### ISSUE THREAD

**Issue by 99119240** [a2x/cs2-dumper#96]

**Comment by lum0022** [comment]
please switch back or provide the old version of the dumper

**Comment by Kuhicop** [comment]
I need the client.dll offsets :(

Managed to get this ones:
```
constexpr ptrdiff_t dwLocalPlayerPawn = 0x17361E8;
constexpr ptrdiff_t dwEntityList = 0x18C1DB8;
constexpr ptrdiff_t dwViewAngles = 0x192F940;
constexpr ptrdiff_t dwViewMatrix = 0x19231B0;
```

But still looking for this values:
```
constexpr ptrdiff_t m_hPlayerPawn = 0x7E4;
constexpr ptrdiff_t m_bPawnIsAlive = 0x7EC;
constexpr ptrdiff_t m_iTeamNum = 0x3CB;
constexpr ptrdiff_t m_iHealth = 0x334;
constexpr ptrdiff_t m_sSanitizedPlayerName = 0x748;
constexpr ptrdiff_t m_iCompetitiveRanking = 0x768;
constexpr ptrdiff_t m_iCompetitiveWins = 0x76C;
constexpr ptrdiff_t m_vOldOrigin = 0x127C;
constexpr ptrdiff_t m_flDetectedByEnemySensorTime = 0x1440;
```

**Comment by 99119240** [comment]
I agree with all of yall for a switch or upload the old one.

**Comment by Kuhicop** [comment]
[CS DUMPER.zip](https://github.com/a2x/cs2-dumper/files/14847313/CS.DUMPER.zip)
Here is my old version but client.dll is throwing empty output anyways, probably signatures must be updated or something

**Comment by 99119240** [comment]
I went to one of the newest forks and built the old ver

**Comment by 99119240** [comment]
> [CS DUMPER.zip](https://github.com/a2x/cs2-dumper/files/14847313/CS.DUMPER.zip) Here is my old version but client.dll is throwing empty output anyways, probably signatures must be updated or something
> 
> Here you can get the file when it's uploaded after analyzed if you doubt about it's origin and stuff: https://www.unknowncheats.me/forum/4039142-post2.html

Also can u upload this to your github for me to download??

**Comment by Kuhicop** [comment]
> > [CS DUMPER.zip](https://github.com/a2x/cs2-dumper/files/14847313/CS.DUMPER.zip) Here is my old version but client.dll is throwing empty output anyways, probably signatures must be updated or something
> > Here you can get the file when it's uploaded after analyzed if you doubt about it's origin and stuff: [unknowncheats.me/forum/4039142-post2.html](https://www.unknowncheats.me/forum/4039142-post2.html)
> 
> Also can u upload this to your github for me to download??

https://github.com/Kuhicop/CS2-DUMPER-OLD

**Comment by 99119240** [comment]
thinks but since client.dll aint working some issues arise

**Comment by 99119240** [comment]
also i thought this was old

**Comment by 99119240** [comment]
@a2x  BRO PLEASE>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by Trixxen** [comment]
I agree new version is ass and broke everything
