### ISSUE TITLE
Offets.cs is outdated.

### ISSUE THREAD

**Issue by SoraAurora** [a2x/cs2-dumper#98]
For anyone needed the new one 

// Generated using https://github.com/a2x/cs2-dumper
// 2024-04-03 06:26:52.824504500 UTC

namespace CS2Dumper.Offsets {
    // Module: client.dll
    public static class ClientDll {
        public const nint dwCSGOInput = 0x192A5B0;
        public const nint dwEntityList = 0x18C1DB8;
        public const nint dwGameEntitySystem = 0x19DF760;
        public const nint dwGameEntitySystem_getHighestEntityIndex = 0x1510;
        public const nint dwGameRules = 0x191EC70;
        public const nint dwGlobalVars = 0x1729BA0;
        public const nint dwGlowManager = 0x191F090;
        public const nint dwLocalPlayerController = 0x1911578;
        public const nint dwLocalPlayerPawn = 0x17361E8;
        public const nint dwPlantedC4 = 0x1927A68;
        public const nint dwPrediction = 0x17360B0;
        public const nint dwSensitivity = 0x191F9B8;
        public const nint dwSensitivity_sensitivity = 0x40;
        public const nint dwViewAngles = 0x192F940;
        public const nint dwViewMatrix = 0x19231B0;
        public const nint dwViewRender = 0x19239B0;
    }
    // Module: engine2.dll
    public static class Engine2Dll {
        public const nint dwBuildNumber = 0x515564;
        public const nint dwNetworkGameClient = 0x514AC8;
        public const nint dwNetworkGameClient_deltaTick = 0x258;
        public const nint dwNetworkGameClient_getLocalPlayer = 0xF0;
        public const nint dwNetworkGameClient_getMaxClients = 0x250;
        public const nint dwNetworkGameClient_signOnState = 0x240;
        public const nint dwWindowHeight = 0x5CDD14;
        public const nint dwWindowWidth = 0x5CDD10;
    }
    // Module: inputsystem.dll
    public static class InputsystemDll {
        public const nint dwInputSystem = 0x367A0;
    }
    // Module: matchmaking.dll
    public static class MatchmakingDll {
        public const nint dwGameTypes = 0x1D21E0;
        public const nint dwGameTypes_mapName = 0x1D2300;
    }
}

**Comment by 99119240** [comment]
if u run the offsets getter tool rn all the sigs are diff @a2x  FIX

**Comment by 99119240** [comment]
@a2x fux
