### ISSUE TITLE
getting empty dumps

### ISSUE THREAD

**Issue by Txreq** [a2x/cs2-dumper#99]
I'm not sure why but the output I'm getting is very unlike the hosted [one in the repo](https://github.com/a2x/cs2-dumper/tree/main/output) because most of the dumped DLLs I got are empty. I even tried running the executable as administrator but that had no effect. Here's an example of what I'm getting:
```rs
#![allow(non_upper_case_globals, non_camel_case_types, unused)]
pub mod cs2_dumper {
    pub mod schemas {
    }
}
``` 
[client.dll.rs](https://github.com/a2x/cs2-dumper/blob/main/output/client.dll.rs)

- Latest [version](https://github.com/a2x/cs2-dumper/releases/tag/0.1.0), built from source

**Comment by lapoyy99** [comment]
same issue here 
```
// Generated using https://github.com/a2x/cs2-dumper
// 2024-04-03 09:18:51.398803700 UTC

namespace CS2Dumper.Schemas {
}
```

**Comment by SoraAurora** [comment]
same issue here but the Offset.cs is different while as client.dll.cs is the same as last update
